export type PricingPackage = {
  name: string;
  price: string;
  period: string;
  savings?: string;
  description: string;
  features: string[];
  cta: string;
  popular: boolean;
  addOns?: string[];
};

export type ComparisonRow = {
  feature: string;
  basic: string | boolean;
  standard: string | boolean;
  premium: string | boolean;
};

export type ServicePricing = {
  id: string;
  name: string;
  category: string;
  tagline: string;
  packages: [PricingPackage, PricingPackage, PricingPackage];
  comparison: ComparisonRow[];
  faqs: { q: string; a: string }[];
  timeline: string;
  technologies: string[];
  support: string;
  guarantee?: string;
};

const allServices: ServicePricing[] = [
{
    id: "ai-automation",
    name: "AI Receptionist",
    category: "AI & Automation",
    tagline: "One flagship AI front desk — voice, WhatsApp, and web chat. Answers, books, and follows up 24/7.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month",
        description: "Put an AI assistant on your website that answers patients and captures every lead, 24/7.",
        features: [
          "AI website chat assistant (trained on your clinic)",
          "Answers FAQs: prices, hours, services, directions",
          "Captures name + contact from every visitor",
          "Instant email alerts on new leads",
          "Appointment request booking",
          "Up to 500 conversations / month",
          "Setup, training & go-live in 5 days",
        ],
        cta: "Start with Basic",
        popular: false,
        addOns: ["Voice notes (patients speak) from $99/mo", "Extra conversations from $49/mo"],
      },
      {
        name: "Standard",
        price: "$1,000",
        period: "/ month",
        savings: "Most popular with busy clinics",
        description: "A full AI receptionist across web + WhatsApp that books patients and confirms automatically.",
        features: [
          "Everything in Basic",
          "AI receptionist on website + WhatsApp",
          "Books appointments straight into your calendar",
          "Automatic booking confirmations (email + WhatsApp)",
          "Automated appointment reminders (cut no-shows)",
          "Voice notes — patients can speak to the AI",
          "Up to 2,000 conversations / month",
          "Live analytics dashboard",
        ],
        cta: "Get Standard",
        popular: true,
        addOns: ["Live voice-call agent from $199/mo", "CRM/EHR sync from $149/mo"],
      },
      {
        name: "Premium",
        price: "$2,000",
        period: "/ month",
        description: "A real-time voice + chat AI agent that runs your front desk end to end, at scale.",
        features: [
          "Everything in Standard",
          "Live real-time voice agent (patients call your site)",
          "Urgency triage + instant priority alerts to staff",
          "Post-visit review requests (grow your Google rating)",
          "Full CRM / EHR / calendar integration",
          "Multi-location & multi-team support",
          "Unlimited conversations",
          "Dedicated success manager + priority support",
        ],
        cta: "Go Premium",
        popular: false,
        addOns: ["Custom workflow automations quoted per build"],
      },
    ],
    comparison: [
      { feature: "Website chat assistant", basic: true, standard: true, premium: true },
      { feature: "WhatsApp AI receptionist", basic: false, standard: true, premium: true },
      { feature: "Books into your calendar", basic: "Requests", standard: true, premium: true },
      { feature: "Voice notes (patient speaks)", basic: false, standard: true, premium: true },
      { feature: "Live real-time voice agent", basic: false, standard: false, premium: true },
      { feature: "Automated reminders", basic: false, standard: true, premium: true },
      { feature: "Urgency triage alerts", basic: false, standard: false, premium: true },
      { feature: "Review collection", basic: false, standard: false, premium: true },
      { feature: "Monthly conversations", basic: "500", standard: "2,000", premium: "Unlimited" },
    ],
    faqs: [
      { q: "What is the AI Receptionist?", a: "It's your clinic's AI front desk — one product with clear channels (website chat, WhatsApp, and voice on higher tiers). It answers patient questions, books appointments, sends reminders, and follows up 24/7." },
      { q: "Is this different from a separate WhatsApp bot or voice agent?", a: "No — those are channels of the same AI Receptionist, not separate products. You pick the channels you need; Standard includes web + WhatsApp, Premium adds live voice." },
      { q: "Will it work with my current systems?", a: "Yes. Standard and Premium integrate with your calendar, CRM, and EHR so bookings and patient details flow in automatically — no double entry." },
      { q: "How fast can we go live?", a: "Typically 5 business days. We train the AI on your services, prices, and hours, test it with you, then switch it on." },
      { q: "Is it only for dental clinics?", a: "No — it works for dental, aesthetic, dermatology, and multi-specialty clinics. It's trained on your specific services." },
    ],
    timeline: "Live in 5 business days",
    technologies: ["GPT-4o", "Realtime voice AI", "WhatsApp Business API", "Calendar & EHR integrations"],
    support: "Included ongoing support; dedicated success manager on Premium.",
    guarantee: "30-day money-back guarantee if it doesn't reduce your missed patients.",
  },
{
    id: "healthcare-website",
    name: "Healthcare Website Development",
    category: "Web & App",
    tagline: "Patient-converting websites built for modern US healthcare practices.",
    packages: [
      {
        name: "Basic",
        price: "$1,500",
        period: "one-time",
        description: "A professional, mobile-optimized site for new practices ready to establish a credible online presence.",
        features: [
          "5-page custom website (Home, Services, About, Blog, Contact)",
          "Mobile-first responsive design",
          "HIPAA-friendly contact & inquiry forms",
          "Google Business Profile integration",
          "On-page SEO (titles, meta tags, schema)",
          "Appointment request form",
          "SSL setup & security hardening",
          "Sub-2-second page load optimization",
          "Google Analytics 4 setup",
          "10-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Logo & brand identity from $799", "Blog content package from $299/mo"],
      },
      {
        name: "Standard",
        price: "$3,000",
        period: "one-time",
        savings: "Most chosen by growing practices",
        description: "A conversion-optimized, fully branded website with patient booking — built to turn visitors into patients.",
        features: [
          "Up to 12 pages including service-specific landing pages",
          "Custom UI design aligned to your brand",
          "HIPAA-compliant patient intake forms",
          "Online booking integration (Zocdoc, Calendly, or custom)",
          "Google Analytics 4 + conversion tracking",
          "Core Web Vitals optimized (90+ PageSpeed score)",
          "ADA accessibility compliance",
          "Live chat widget integration",
          "Full schema markup (MedicalBusiness, Physician)",
          "3 rounds of design revisions",
          "30-day post-launch support",
          "21-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Monthly maintenance from $149/mo", "SEO retainer from $599/mo"],
      },
      {
        name: "Premium",
        price: "$5,000",
        period: "one-time",
        description: "Enterprise-grade healthcare platform for multi-location groups, DSOs, and ambitious independent practices.",
        features: [
          "Unlimited pages + multi-location architecture",
          "Fully custom UI/UX with motion & micro-interactions",
          "EMR/EHR system integration",
          "Patient portal with secure login",
          "Telemedicine booking flow",
          "Multi-provider scheduling system",
          "AI chatbot integration",
          "HIPAA compliance review",
          "Heatmap & CRO setup (Hotjar or FullStory)",
          "Custom admin dashboard",
          "Unlimited revisions during build",
          "60-day post-launch support",
          "30-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing SEO from $1,199/mo", "AI Receptionist from $399/mo"],
      },
    ],
    comparison: [
      { feature: "Number of pages", basic: "5 pages", standard: "Up to 12", premium: "Unlimited" },
      { feature: "Custom design", basic: "Template-based", standard: "Custom", premium: "Fully custom + motion" },
      { feature: "Mobile optimization", basic: true, standard: true, premium: true },
      { feature: "Online booking integration", basic: false, standard: true, premium: true },
      { feature: "HIPAA-compliant forms", basic: "Basic forms", standard: "HIPAA-compliant", premium: "HIPAA + patient portal" },
      { feature: "EMR/EHR integration", basic: false, standard: false, premium: true },
      { feature: "PageSpeed score", basic: "70+", standard: "90+", premium: "95+" },
      { feature: "ADA accessibility", basic: false, standard: true, premium: true },
      { feature: "Multi-location support", basic: false, standard: false, premium: true },
      { feature: "AI chatbot", basic: false, standard: false, premium: true },
      { feature: "Post-launch support", basic: "None", standard: "30 days", premium: "60 days" },
      { feature: "Design revisions", basic: "1 round", standard: "3 rounds", premium: "Unlimited" },
    ],
    faqs: [
      { q: "How long does it take to build a healthcare website?", a: "Basic sites deliver in 10 business days, Standard in 21, and Premium in 30. We run a structured sprint — discovery, wireframes, design, development, QA, then launch — with stage updates so you're never in the dark." },
      { q: "Is the website HIPAA compliant?", a: "We don't store PHI directly on the site. All forms and third-party tools are configured to HIPAA-friendly standards. For a signed BAA, we partner with certified hosting providers or work with your compliance team." },
      { q: "Do I own the website after it's built?", a: "100%. You own the code, domain, and every asset. Full repo access is handed off at launch. We never lock you into proprietary platforms." },
      { q: "Can you migrate my existing website?", a: "Yes — content migration and URL redirects are included in Standard and Premium so your existing SEO equity carries over." },
      { q: "What CMS do you use?", a: "We build on Next.js for peak performance and SEO, with Sanity or a headless CMS for easy content updates — no developer needed for routine edits." },
    ],
    timeline: "10–30 business days",
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Sanity CMS", "Vercel", "Firebase"],
    support: "30–60 days post-launch support included based on plan",
    guarantee: "Not happy with the first design round? We redesign it at zero charge.",
  },
{
    id: "mobile-app",
    name: "Mobile App Development",
    category: "Web & App",
    tagline: "Native-quality healthcare apps that patients actually use — built fast, shipped clean.",
    packages: [
      {
        name: "Basic",
        price: "$5,000",
        period: "one-time",
        description: "A polished single-platform app for practices ready to give patients a branded mobile experience.",
        features: [
          "iOS or Android (single platform)",
          "Up to 8 screens",
          "Appointment request module",
          "Push notification support",
          "Basic user profile (name, DOB, contact)",
          "REST API backend",
          "App Store / Play Store submission",
          "60-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Second platform add-on $4,999", "App maintenance from $149/mo"],
      },
      {
        name: "Standard",
        price: "$15,000",
        period: "one-time",
        savings: "Best value for most practices",
        description: "A dual-platform patient app with real booking, secure messaging, and a health record viewer.",
        features: [
          "iOS + Android (both platforms)",
          "Up to 18 screens",
          "Full appointment booking with calendar sync",
          "Secure in-app patient messaging",
          "Health record & prescription viewer",
          "Push + SMS notifications",
          "Payment integration (Stripe)",
          "Custom branded splash & onboarding",
          "Admin dashboard for staff",
          "90-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Telemedicine module from $4,999", "AI triage chatbot from $2,999"],
      },
      {
        name: "Premium",
        price: "$30,000",
        period: "one-time",
        description: "A full healthcare super-app — iOS, Android, and web — with AI features, telemedicine, and EMR integration.",
        features: [
          "iOS + Android + Progressive Web App",
          "Unlimited screens",
          "Full EMR/EHR integration",
          "Telemedicine video visits",
          "AI symptom checker + triage",
          "Lab results viewer + push alerts",
          "Multi-provider scheduling",
          "Insurance card capture",
          "Biometric authentication",
          "Offline mode support",
          "Custom backend & admin portal",
          "120-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Dedicated post-launch SLA from $599/mo"],
      },
    ],
    comparison: [
      { feature: "Platforms", basic: "iOS or Android", standard: "iOS + Android", premium: "iOS + Android + Web" },
      { feature: "Number of screens", basic: "Up to 8", standard: "Up to 18", premium: "Unlimited" },
      { feature: "Appointment booking", basic: "Request only", standard: "Full booking + calendar sync", premium: "Multi-provider booking" },
      { feature: "Secure patient messaging", basic: false, standard: true, premium: true },
      { feature: "Health records viewer", basic: false, standard: true, premium: true },
      { feature: "EMR/EHR integration", basic: false, standard: false, premium: true },
      { feature: "Telemedicine", basic: false, standard: "Add-on", premium: true },
      { feature: "Payment integration", basic: false, standard: true, premium: true },
      { feature: "AI features", basic: false, standard: false, premium: true },
      { feature: "Admin dashboard", basic: false, standard: true, premium: true },
      { feature: "Delivery time", basic: "60 days", standard: "90 days", premium: "120 days" },
    ],
    faqs: [
      { q: "Do you build native or cross-platform apps?", a: "We use React Native for cross-platform builds that feel fully native — one codebase, two stores, no quality compromise." },
      { q: "How long does App Store approval take?", a: "Apple typically reviews in 1–3 days; Google Play in 1–7 days. We prep all assets and metadata to minimize rejections." },
      { q: "Can the app integrate with our existing EHR?", a: "Yes. Premium includes full EMR/EHR integration. Standard includes a record viewer that connects to most major EHRs via HL7 FHIR API." },
      { q: "Who manages the app after launch?", a: "You own it entirely. We offer maintenance plans from $149/mo for updates, OS compatibility fixes, and ongoing improvements." },
      { q: "Is the patient data HIPAA compliant?", a: "All patient data is encrypted in transit and at rest. We use HIPAA-eligible cloud infrastructure and can work with your compliance officer on a BAA." },
    ],
    timeline: "60–120 business days",
    technologies: ["React Native", "Expo", "Node.js", "Firebase", "PostgreSQL", "Stripe", "Twilio"],
    support: "App Store submission + 30-day bug-fix period included",
    guarantee: "Bug-free launch guarantee — we fix any post-launch defects within 30 days at no charge.",
  },
{
    id: "whatsapp-automation",
    name: "WhatsApp AI Automation",
    category: "AI & Automation",
    tagline: "Turn your WhatsApp number into a 24/7 patient engagement engine.",
    packages: [
      {
        name: "Basic",
        price: "$249",
        period: "/ month",
        description: "Automated appointment reminders and instant replies — stop losing patients to unanswered WhatsApp messages.",
        features: [
          "500 outbound messages / month",
          "Automated appointment reminders",
          "Instant auto-reply for common questions",
          "2 pre-built conversation flows",
          "Business hours configuration",
          "Monthly delivery report",
          "5-day setup",
        ],
        cta: "Get Started",
        popular: false,
        addOns: ["Additional 500 messages +$49/mo", "Broadcast campaigns +$99/mo"],
      },
      {
        name: "Standard",
        price: "$499",
        period: "/ month",
        savings: "Most practices recoup the cost in 2 recovered bookings",
        description: "A full patient journey on WhatsApp — from first inquiry through confirmed booking and post-visit follow-up.",
        features: [
          "2,500 outbound messages / month",
          "AI-powered instant replies (NLP)",
          "Full appointment booking flow",
          "Automated pre- and post-visit sequences",
          "8 custom conversation flows",
          "Broadcast campaigns (promotions, recalls)",
          "Read receipt & engagement tracking",
          "CRM lead sync",
          "Conversation analytics dashboard",
          "3-day setup",
        ],
        cta: "Get Started",
        popular: true,
        addOns: ["Additional flows +$99 each", "Multi-agent inbox +$149/mo"],
      },
      {
        name: "Premium",
        price: "$999",
        period: "/ month",
        description: "Unlimited messaging, AI-driven conversations, EMR sync, and broadcast campaigns — the full WhatsApp automation stack.",
        features: [
          "Unlimited outbound messages",
          "Advanced NLP AI replies",
          "Unlimited conversation flows",
          "EMR/EHR appointment sync",
          "Multi-agent team inbox with routing",
          "Broadcast campaigns with segmentation",
          "No-show recovery sequences",
          "Review generation flows (Google, Healthgrades)",
          "Real-time conversation analytics",
          "Dedicated onboarding + monthly strategy call",
        ],
        cta: "Book a Demo",
        popular: false,
        addOns: ["AI voice escalation from $299/mo"],
      },
    ],
    comparison: [
      { feature: "Monthly messages", basic: "500", standard: "2,500", premium: "Unlimited" },
      { feature: "AI-powered replies", basic: false, standard: true, premium: true },
      { feature: "Appointment booking flow", basic: false, standard: true, premium: true },
      { feature: "Custom conversation flows", basic: "2 flows", standard: "8 flows", premium: "Unlimited" },
      { feature: "Broadcast campaigns", basic: "Add-on", standard: true, premium: "With segmentation" },
      { feature: "EMR/EHR sync", basic: false, standard: false, premium: true },
      { feature: "Multi-agent inbox", basic: false, standard: "Add-on", premium: true },
      { feature: "Review generation", basic: false, standard: false, premium: true },
      { feature: "No-show recovery", basic: "Basic reminders", standard: "Reminder sequences", premium: "Full recovery flows" },
      { feature: "CRM sync", basic: false, standard: true, premium: true },
      { feature: "Analytics", basic: "Monthly report", standard: "Dashboard", premium: "Real-time + AI insights" },
      { feature: "Setup time", basic: "5 days", standard: "3 days", premium: "2 days" },
    ],
    faqs: [
      { q: "Do you use the official WhatsApp Business API?", a: "Yes — we integrate through Meta's official Business API, which means no risk of your number being banned and full broadcast capability." },
      { q: "Can patients book appointments directly in WhatsApp?", a: "Yes on Standard and Premium. The AI guides them through a natural-language booking flow, checks availability, confirms, and sends a calendar invite." },
      { q: "Is patient data safe over WhatsApp?", a: "WhatsApp uses end-to-end encryption for messages. We don't store PHI beyond what's needed for booking sync, and comply with HIPAA data handling principles." },
      { q: "Can I still reply to patients manually?", a: "Absolutely. The AI handles routine messages automatically. You — or your team — can jump into any conversation at any time via the team inbox." },
      { q: "What's the difference between this and a chatbot?", a: "WhatsApp automation lives on a channel patients already use daily, with higher open rates (98% vs. email's ~20%). The AI is trained on your specific practice, not generic responses." },
    ],
    timeline: "2–5 business days to go live",
    technologies: ["WhatsApp Business API", "Meta Cloud API", "OpenAI", "Twilio", "Zapier", "Firebase"],
    support: "Uptime monitoring + message delivery guarantee included",
    guarantee: "If your message delivery rate falls below 95% for any reason, we issue a service credit.",
  },
{
    id: "emr-ehr",
    name: "EMR / EHR Software",
    category: "Integration",
    tagline: "Purpose-built electronic health records for modern healthcare practices — go paperless in weeks, not years.",
    packages: [
      {
        name: "Basic",
        price: "$4,999",
        period: "one-time",
        description: "A fully digital patient record system for solo or small practices ready to eliminate paper charts.",
        features: [
          "1 provider, 1 location",
          "Digital patient charts & records",
          "SOAP note templates",
          "Basic appointment scheduling",
          "Prescription generation (PDF)",
          "Patient demographics & history",
          "Data import from Excel/CSV",
          "Role-based staff access",
          "6-month support included",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Additional provider +$499", "Patient mobile app from $4,999"],
      },
      {
        name: "Standard",
        price: "$9,999",
        period: "one-time",
        savings: "Most practices recover the investment in under 90 days",
        description: "A complete EHR for growing multi-provider practices — scheduling, billing, prescriptions, and patient management unified.",
        features: [
          "Up to 10 providers, 3 locations",
          "Full patient chart management",
          "Custom specialty-specific note templates",
          "Advanced scheduling with provider calendars",
          "Digital prescriptions (DEA-compliant e-prescribing ready)",
          "Billing & invoicing module",
          "Insurance claim tracking",
          "Lab results management",
          "Patient portal (web)",
          "Custom reporting dashboard",
          "1-year support included",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Branded patient mobile app from $9,999", "Telehealth module +$3,999"],
      },
      {
        name: "Premium",
        price: "From $19,999",
        period: "one-time",
        description: "Enterprise EHR for large groups, DSOs, and multi-specialty networks — infinitely scalable, deeply customized.",
        features: [
          "Unlimited providers & locations",
          "Custom clinical workflow builder",
          "Multi-specialty template library",
          "Advanced scheduling with resource management",
          "Full RCM (revenue cycle management)",
          "FHIR R4 / HL7 interoperability",
          "Lab & radiology DICOM viewer",
          "Telemedicine built-in",
          "AI clinical decision support",
          "Custom analytics & business intelligence",
          "White-label branded patient app",
          "2-year support included",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing support retainer from $999/mo", "Staff training workshop from $1,499"],
      },
    ],
    comparison: [
      { feature: "Providers", basic: "1", standard: "Up to 10", premium: "Unlimited" },
      { feature: "Locations", basic: "1", standard: "Up to 3", premium: "Unlimited" },
      { feature: "Patient scheduling", basic: "Basic", standard: "Advanced multi-provider", premium: "Resource management" },
      { feature: "Billing & invoicing", basic: false, standard: true, premium: "Full RCM" },
      { feature: "e-Prescribing", basic: "PDF only", standard: "DEA-compliant ready", premium: "Full e-prescribing" },
      { feature: "Lab results", basic: false, standard: true, premium: "DICOM viewer" },
      { feature: "Patient portal", basic: false, standard: "Web portal", premium: "Web + branded app" },
      { feature: "FHIR/HL7", basic: false, standard: false, premium: true },
      { feature: "Telemedicine", basic: false, standard: "Add-on", premium: true },
      { feature: "AI decision support", basic: false, standard: false, premium: true },
      { feature: "Post-delivery support", basic: "6 months", standard: "1 year", premium: "2 years" },
    ],
    faqs: [
      { q: "Is the EHR HIPAA compliant?", a: "Yes. All patient data is stored on HIPAA-eligible cloud infrastructure, encrypted at rest and in transit, with role-based access controls and full audit logging. We sign a BAA." },
      { q: "How long does implementation take?", a: "Basic: 4–6 weeks. Standard: 8–10 weeks. Premium: 12–16 weeks, depending on custom requirements. We include data migration from your existing records." },
      { q: "Can you migrate our existing patient records?", a: "Yes — data migration is included in all plans. We import from paper scans, Excel/CSV, or your current EHR system." },
      { q: "Does it work for our specialty?", a: "We've built EHRs for dental, dermatology, aesthetic, OB/GYN, orthopedics, and multi-specialty practices. Note templates and workflows are customized per specialty." },
      { q: "Can patients access their records online?", a: "Standard includes a web patient portal. Premium includes a white-labeled mobile app for iOS and Android." },
    ],
    timeline: "4–16 weeks depending on plan and customization",
    technologies: ["Next.js", "PostgreSQL", "AWS", "HL7 FHIR", "Twilio", "Stripe", "Firebase Auth"],
    support: "6 months to 2 years of post-delivery support included by plan",
    guarantee: "HIPAA-compliant or we fix it — guaranteed before final delivery.",
  },
{
    id: "local-seo",
    name: "Local SEO",
    category: "Marketing",
    tagline: "Rank first when patients search 'dentist near me' — dominate your local market.",
    packages: [
      {
        name: "Basic",
        price: "$300",
        period: "/ month",
        description: "A strong local SEO foundation for single-location practices ready to start appearing in Google's local pack.",
        features: [
          "1 location optimized",
          "10 target local keywords",
          "Google Business Profile optimization",
          "Monthly citation building (10 directories)",
          "NAP consistency audit & fix",
          "Review monitoring alerts",
          "Geo-targeted on-page optimization",
          "Monthly ranking report",
        ],
        cta: "Start Growing",
        popular: false,
        addOns: ["Additional location +$199/mo", "Review generation campaign +$149/mo"],
      },
      {
        name: "Standard",
        price: "$500",
        period: "/ month",
        savings: "Average client sees local pack ranking in 60–90 days",
        description: "An aggressive local presence strategy for multi-location practices ready to own their ZIP code.",
        features: [
          "Up to 3 locations optimized",
          "25 target local keywords",
          "Full Google Business Profile management",
          "Monthly citation building (25 directories)",
          "Local link building (5 links/mo)",
          "Review generation system",
          "Competitor ranking tracking",
          "Hyperlocal content updates (2/mo)",
          "Bi-weekly ranking report",
          "Monthly strategy call",
        ],
        cta: "Start Growing",
        popular: true,
        addOns: ["4th+ location at $199/mo each", "Google Ads synergy package +$499/mo"],
      },
      {
        name: "Premium",
        price: "$700",
        period: "/ month",
        description: "Total local market domination — 5+ locations, aggressive link building, and review management at scale.",
        features: [
          "Up to 5 locations (additional +$149/mo each)",
          "50+ target local keywords",
          "Full GBP management with weekly posts",
          "Citation building (50 directories/mo)",
          "Local PR + link building (15 links/mo)",
          "Automated review generation system",
          "Review response management",
          "Local competitor conquesting",
          "Weekly ranking dashboard",
          "Dedicated local SEO strategist",
          "Weekly check-in call",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["National SEO expansion from $599/mo add-on"],
      },
    ],
    comparison: [
      { feature: "Locations", basic: "1", standard: "Up to 3", premium: "Up to 5" },
      { feature: "Target keywords", basic: "10", standard: "25", premium: "50+" },
      { feature: "GBP management", basic: "Setup only", standard: "Full management", premium: "Full + weekly posts" },
      { feature: "Monthly citations", basic: "10 directories", standard: "25 directories", premium: "50 directories" },
      { feature: "Local link building", basic: false, standard: "5 links/mo", premium: "15 links/mo" },
      { feature: "Review generation", basic: "Monitoring only", standard: true, premium: "Automated + responses" },
      { feature: "Competitor tracking", basic: false, standard: true, premium: "Conquesting strategy" },
      { feature: "Local content", basic: false, standard: "2 updates/mo", premium: "Weekly GBP posts" },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Strategy calls", basic: false, standard: "Monthly", premium: "Weekly" },
      { feature: "Dedicated strategist", basic: false, standard: false, premium: true },
    ],
    faqs: [
      { q: "How long does local SEO take to show results?", a: "Most practices see movement in the local 3-pack within 60–90 days. Competitive markets may take 90–120 days. Unlike ads, local SEO results compound over time." },
      { q: "What is Google Business Profile optimization?", a: "We optimize every field — categories, services, attributes, photos, Q&A, and regular posts — to maximize your relevance score in Google's local algorithm." },
      { q: "What's the difference between Local SEO and regular SEO?", a: "Local SEO targets 'near me' searches and the Google Maps 3-pack. Regular SEO targets broader informational keywords. For practices, Local SEO typically delivers faster patient ROI." },
      { q: "Do you manage our Google reviews?", a: "Standard and Premium include review generation (automated asks post-visit) and monitoring. Premium adds professional response management to every review." },
      { q: "Can you help multiple office locations?", a: "Yes — Standard covers up to 3 locations and Premium up to 5, each with independent GBP management, citations, and location-specific keyword targeting." },
    ],
    timeline: "Results typically visible in 60–90 days",
    technologies: ["Google Business Profile", "BrightLocal", "Ahrefs", "Moz Local", "SEMrush", "Google Search Console"],
    support: "Monthly report + dedicated account manager on Standard and Premium",
    guarantee: "If we don't improve your local ranking by month 3, you get month 4 free.",
  },
{
    id: "seo",
    name: "SEO",
    category: "Marketing",
    tagline: "Long-term organic visibility that compounds — ranking for the keywords your patients actually search.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month",
        description: "On-page SEO and technical foundations for practices ready to start earning organic traffic.",
        features: [
          "10 pages optimized / month",
          "15 target keywords",
          "Full technical SEO audit",
          "On-page optimization (titles, H-tags, meta, schema)",
          "XML sitemap + robots.txt management",
          "Monthly keyword movement report",
          "Core Web Vitals monitoring",
        ],
        cta: "Start Growing",
        popular: false,
        addOns: ["Blog content 2 posts/mo +$299", "Link building starter +$299/mo"],
      },
      {
        name: "Standard",
        price: "$700",
        period: "/ month",
        savings: "Average 4× ROI within 6 months for healthcare clients",
        description: "Full-spectrum SEO with content creation, link building, and competitor displacement.",
        features: [
          "25 pages optimized / month",
          "35 target keywords",
          "Technical SEO (crawl errors, page speed, structured data)",
          "4 SEO-optimized blog posts / month",
          "Link building (5 DR40+ backlinks / month)",
          "Competitor gap analysis",
          "Google Search Console management",
          "Bi-weekly ranking report",
          "Monthly strategy call",
        ],
        cta: "Start Growing",
        popular: true,
        addOns: ["Additional 5 links/mo +$399", "Local SEO package +$499/mo"],
      },
      {
        name: "Premium",
        price: "$1,000",
        period: "/ month",
        description: "Aggressive, authority-building SEO for practices ready to own page 1 for their entire service menu.",
        features: [
          "50+ pages optimized / month",
          "75+ target keywords",
          "Full technical SEO including JS rendering",
          "8 SEO blog posts + 2 pillar pages / month",
          "Link building (15 DR50+ links / month)",
          "Digital PR campaigns",
          "Featured snippet targeting",
          "Topical authority mapping",
          "Schema markup for all content types",
          "Weekly ranking dashboard",
          "Dedicated SEO strategist",
          "Weekly check-in",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Paid ads integration from $499/mo"],
      },
    ],
    comparison: [
      { feature: "Pages optimized / month", basic: "10", standard: "25", premium: "50+" },
      { feature: "Target keywords", basic: "15", standard: "35", premium: "75+" },
      { feature: "Technical SEO", basic: "Audit only", standard: "Ongoing", premium: "Full + JS rendering" },
      { feature: "Blog content / month", basic: "None", standard: "4 posts", premium: "8 posts + 2 pillar pages" },
      { feature: "Link building / month", basic: "None", standard: "5 DR40+ links", premium: "15 DR50+ links" },
      { feature: "Digital PR", basic: false, standard: false, premium: true },
      { feature: "Competitor gap analysis", basic: false, standard: true, premium: "Ongoing" },
      { feature: "Schema markup", basic: "Basic", standard: "Full", premium: "All content types" },
      { feature: "Featured snippet targeting", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Dedicated strategist", basic: false, standard: false, premium: true },
    ],
    faqs: [
      { q: "How long does it take to rank on Google?", a: "For competitive healthcare keywords, typically 3–6 months of consistent work. Less competitive terms often rank in 4–8 weeks. Unlike paid ads, organic rankings continue delivering results after the campaign ends." },
      { q: "Do you create the content or do we?", a: "On Standard and Premium, we handle all content creation — researched, clinician-reviewed, and optimized for ranking and patient conversion." },
      { q: "What's your link building approach?", a: "We earn links through digital PR, guest posts on medical and health publications, and relationship-based outreach — never spammy link farms." },
      { q: "How do you measure success?", a: "Keyword rankings, organic traffic, new patient inquiries from organic, and conversion rate from organic landing pages — all tracked in your reporting dashboard." },
      { q: "Can SEO work alongside our paid ads?", a: "Absolutely — SEO and paid ads complement each other. SEO covers long-term organic growth while ads drive immediate traffic. We offer a synergy package when combining both." },
    ],
    timeline: "First ranking movements typically in 60–90 days",
    technologies: ["Ahrefs", "SEMrush", "Google Search Console", "Screaming Frog", "Surfer SEO", "Google Analytics 4"],
    support: "Monthly reporting + account manager included on all plans",
    guarantee: "If your organic traffic doesn't increase in 90 days, we work for free until it does.",
  },
{
    id: "google-ads",
    name: "Google Ads Management",
    category: "Marketing",
    tagline: "Paid search that puts your practice in front of patients searching for exactly what you offer — right now.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month + ad spend",
        description: "Managed Google Search campaigns for practices ready to start generating patient leads from paid traffic.",
        features: [
          "1 Google Search campaign",
          "Manage up to $3,000 ad spend / month",
          "Keyword research & negative keyword setup",
          "Ad copywriting (3 ads per ad group)",
          "Conversion tracking setup",
          "Monthly optimization review",
          "Monthly performance report",
        ],
        cta: "Launch Campaigns",
        popular: false,
        addOns: ["Display/retargeting campaign +$149/mo", "Landing page design +$499 one-time"],
      },
      {
        name: "Standard",
        price: "$900",
        period: "/ month + ad spend",
        savings: "Average 4× ROAS for healthcare practices",
        description: "Multi-campaign Google Ads management with A/B testing and conversion rate optimization.",
        features: [
          "Up to 3 campaigns (Search + Display + Retargeting)",
          "Manage up to $10,000 ad spend / month",
          "Advanced keyword segmentation",
          "Weekly bid strategy optimization",
          "A/B ad copy testing",
          "Advanced conversion tracking (calls, forms, bookings)",
          "Audience & demographic targeting",
          "Competitor conquest campaigns",
          "Bi-weekly performance report",
          "Monthly strategy call",
        ],
        cta: "Launch Campaigns",
        popular: true,
        addOns: ["YouTube ads campaign +$299/mo", "Custom landing page +$799 one-time"],
      },
      {
        name: "Premium",
        price: "$1,400",
        period: "/ month + ad spend",
        description: "Full-funnel Google Ads ecosystem — search, display, YouTube, and Performance Max — with daily optimization.",
        features: [
          "Unlimited campaigns",
          "Unlimited ad spend management",
          "Search + Display + YouTube + Performance Max",
          "Daily bid adjustment & optimization",
          "Smart bidding with custom conversion values",
          "Custom landing pages per campaign",
          "Call tracking with call recording",
          "CRM integration for offline conversion import",
          "Competitive intelligence reporting",
          "Weekly dashboard + dedicated ads manager",
          "Weekly check-in call",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Meta Ads bundle at $1,499/mo (save $500)"],
      },
    ],
    comparison: [
      { feature: "Campaigns managed", basic: "1 Search", standard: "Search + Display + Retargeting", premium: "Unlimited (all types)" },
      { feature: "Monthly ad spend cap", basic: "Up to $3,000", standard: "Up to $10,000", premium: "Unlimited" },
      { feature: "Bid optimization", basic: "Monthly", standard: "Weekly", premium: "Daily" },
      { feature: "A/B ad testing", basic: false, standard: true, premium: true },
      { feature: "Call tracking", basic: "Basic", standard: "Advanced", premium: "Recording + transcripts" },
      { feature: "Custom landing pages", basic: "Not included", standard: "Add-on", premium: "Included" },
      { feature: "YouTube ads", basic: false, standard: "Add-on", premium: true },
      { feature: "Performance Max", basic: false, standard: false, premium: true },
      { feature: "CRM conversion import", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Strategy calls", basic: false, standard: "Monthly", premium: "Weekly" },
    ],
    faqs: [
      { q: "What ad spend budget do I need?", a: "We recommend a minimum of $1,500/mo in ad spend for meaningful results in healthcare. Competitive markets (dental implants, cosmetic surgery) typically need $3,000–$10,000/mo to see significant volume." },
      { q: "How quickly will I see patient leads?", a: "Google Ads can generate leads within 48–72 hours of launch. Expect the first 2 weeks to be an optimization period as the algorithm learns." },
      { q: "Is your management fee separate from ad spend?", a: "Yes — our management fee is separate from the budget you pay directly to Google. You always have full visibility into both." },
      { q: "Do you build the landing pages?", a: "Standard includes landing page recommendations; Premium includes custom landing pages. We can also build dedicated pages as an add-on for Basic clients." },
      { q: "What makes healthcare Google Ads different?", a: "Healthcare ads require careful compliance with Google's healthcare policies, especially for sensitive categories. We know these policies well and ensure your campaigns stay live and compliant." },
    ],
    timeline: "Campaigns live within 3–5 business days",
    technologies: ["Google Ads", "Google Analytics 4", "Google Tag Manager", "CallRail", "HubSpot", "Looker Studio"],
    support: "Account manager + performance reporting included on all plans",
    guarantee: "If we don't improve your cost-per-lead vs. your previous campaigns within 60 days, we refund one month of management.",
  },
{
    id: "meta-ads",
    name: "Meta Ads Management",
    category: "Marketing",
    tagline: "Facebook & Instagram ads that build patient awareness, drive bookings, and grow your practice's revenue.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month + ad spend",
        description: "Foundational Meta advertising for practices ready to reach patients on Facebook and Instagram.",
        features: [
          "2 ad sets (Facebook + Instagram)",
          "Manage up to $3,000 ad spend / month",
          "Core audience targeting setup",
          "Static image + copy creative",
          "Facebook Pixel installation",
          "Monthly campaign optimization",
          "Monthly performance report",
        ],
        cta: "Launch Campaigns",
        popular: false,
        addOns: ["Video ad creative +$399 one-time", "Retargeting setup +$149/mo"],
      },
      {
        name: "Standard",
        price: "$1,000",
        period: "/ month + ad spend",
        savings: "Custom audiences drive 60% lower CPL on average",
        description: "Full-funnel Meta campaigns with lookalike audiences, A/B testing, and creative that converts.",
        features: [
          "5 ad sets across Facebook, Instagram & Messenger",
          "Manage up to $10,000 ad spend / month",
          "Custom audience + lookalike targeting",
          "Carousel + video + story ad formats",
          "A/B creative testing",
          "Retargeting sequences",
          "Lead form ads setup",
          "Weekly bid optimization",
          "Bi-weekly performance report",
          "Monthly strategy call",
        ],
        cta: "Launch Campaigns",
        popular: true,
        addOns: ["Monthly creative refresh +$299", "Influencer coordination +$499/mo"],
      },
      {
        name: "Premium",
        price: "$1,500",
        period: "/ month + ad spend",
        description: "Full-funnel Meta advertising — from cold audience awareness to booked appointments — with daily management.",
        features: [
          "Unlimited ad sets",
          "Unlimited ad spend management",
          "Full funnel (awareness → consideration → conversion)",
          "Advanced Advantage+ AI campaigns",
          "Dynamic ad personalization",
          "Customer list suppression & lookalikes",
          "Monthly creative production (video + static)",
          "Advanced Pixel events + server-side tracking",
          "CRM integration for offline conversions",
          "Daily optimization + weekly dashboard",
          "Dedicated Meta ads specialist",
          "Weekly check-in",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Google Ads bundle at $1,499/mo (save $500)"],
      },
    ],
    comparison: [
      { feature: "Ad sets managed", basic: "2", standard: "5", premium: "Unlimited" },
      { feature: "Monthly ad spend cap", basic: "Up to $3,000", standard: "Up to $10,000", premium: "Unlimited" },
      { feature: "Ad formats", basic: "Static image", standard: "Carousel + video + stories", premium: "All formats + dynamic" },
      { feature: "Custom audiences", basic: "Interest targeting", standard: "Custom + lookalikes", premium: "Advanced + suppression" },
      { feature: "A/B testing", basic: false, standard: true, premium: true },
      { feature: "Retargeting", basic: "Add-on", standard: true, premium: true },
      { feature: "Lead form ads", basic: false, standard: true, premium: true },
      { feature: "Server-side tracking", basic: false, standard: false, premium: true },
      { feature: "CRM offline conversion", basic: false, standard: false, premium: true },
      { feature: "Monthly creative production", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
    ],
    faqs: [
      { q: "What ad spend do I need for Meta ads to work?", a: "We recommend a minimum of $1,500/mo in spend. The algorithm needs data to optimize — higher budgets learn faster and deliver better cost-per-lead." },
      { q: "Can Meta ads work for medical services?", a: "Yes, with the right compliance approach. We know Meta's healthcare advertising policies and structure campaigns to stay approved while still converting effectively." },
      { q: "Do you create the ad creative?", a: "Standard includes creative direction and static ad design. Premium includes a monthly creative production package (video + static). Basic uses provided creative or we create one static set." },
      { q: "How do you track ROI from Meta ads?", a: "We track lead form submissions, website conversions, call-through rates, and — where CRM integration allows — actual booked appointments tied back to specific campaigns." },
      { q: "What's the difference between Facebook and Instagram ads?", a: "We run placements on both by default. Facebook tends to perform better for 35+ age demographics; Instagram for 18–35. We allocate budget dynamically based on performance data." },
    ],
    timeline: "Campaigns live within 3–5 business days",
    technologies: ["Meta Ads Manager", "Meta Pixel", "Meta Conversions API", "HubSpot", "Zapier", "Looker Studio"],
    support: "Account manager + creative consultation included on Standard and Premium",
    guarantee: "If your CPL doesn't improve vs. your prior campaigns within 60 days, we refund one month of management.",
  }
];

// Only services that have a live page on the website
const ACTIVE_IDS = [
  "ai-automation",        // flagship — AI Receptionist (voice + WhatsApp + web chat)
  "healthcare-website",   // /clinic-website-design
  "mobile-app",           // /clinic-mobile-app
  "whatsapp-automation",  // WhatsApp channel packages (optional deep-link)
  "emr-ehr",              // /ehr-platform
  "local-seo",            // /local-seo-for-clinics
  "seo",                  // /seo-for-clinics
  "google-ads",           // /digital-marketing-for-clinics
  "meta-ads",             // /digital-marketing-for-clinics
] as const;

// Order follows ACTIVE_IDS so the flagship (AI Receptionist) leads everywhere.
export const pricingServices = (ACTIVE_IDS as readonly string[])
  .map((id) => allServices.find((s) => s.id === id))
  .filter((s): s is ServicePricing => Boolean(s));

export const serviceCategories = ["All", "Web & App", "AI & Automation", "Marketing", "Integration"] as const;
export type ServiceCategory = typeof serviceCategories[number];
