export type PricingPackage = {
  name: string;
  price: string;
  period: string;
  savings?: string;
  description: string;
  features: string[];
  cta: string;
  popular: boolean;
  addOns?: string[];
};

export type ComparisonRow = {
  feature: string;
  basic: string | boolean;
  standard: string | boolean;
  premium: string | boolean;
};

export type ServicePricing = {
  id: string;
  name: string;
  category: string;
  tagline: string;
  packages: [PricingPackage, PricingPackage, PricingPackage];
  comparison: ComparisonRow[];
  faqs: { q: string; a: string }[];
  timeline: string;
  technologies: string[];
  support: string;
  guarantee?: string;
};

const allServices: ServicePricing[] = [
  // ─── WEB & APP ──────────────────────────────────────────────────────────────
  {
    id: "healthcare-website",
    name: "Healthcare Website Development",
    category: "Web & App",
    tagline: "Patient-converting websites built for modern US healthcare practices.",
    packages: [
      {
        name: "Basic",
        price: "$1,500",
        period: "one-time",
        description: "A professional, mobile-optimized site for new practices ready to establish a credible online presence.",
        features: [
          "5-page custom website (Home, Services, About, Blog, Contact)",
          "Mobile-first responsive design",
          "HIPAA-friendly contact & inquiry forms",
          "Google Business Profile integration",
          "On-page SEO (titles, meta tags, schema)",
          "Appointment request form",
          "SSL setup & security hardening",
          "Sub-2-second page load optimization",
          "Google Analytics 4 setup",
          "10-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Logo & brand identity from $799", "Blog content package from $299/mo"],
      },
      {
        name: "Standard",
        price: "$3,000",
        period: "one-time",
        savings: "Most chosen by growing practices",
        description: "A conversion-optimized, fully branded website with patient booking — built to turn visitors into patients.",
        features: [
          "Up to 12 pages including service-specific landing pages",
          "Custom UI design aligned to your brand",
          "HIPAA-compliant patient intake forms",
          "Online booking integration (Zocdoc, Calendly, or custom)",
          "Google Analytics 4 + conversion tracking",
          "Core Web Vitals optimized (90+ PageSpeed score)",
          "ADA accessibility compliance",
          "Live chat widget integration",
          "Full schema markup (MedicalBusiness, Physician)",
          "3 rounds of design revisions",
          "30-day post-launch support",
          "21-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Monthly maintenance from $149/mo", "SEO retainer from $599/mo"],
      },
      {
        name: "Premium",
        price: "$5,000",
        period: "one-time",
        description: "Enterprise-grade healthcare platform for multi-location groups, DSOs, and ambitious independent practices.",
        features: [
          "Unlimited pages + multi-location architecture",
          "Fully custom UI/UX with motion & micro-interactions",
          "EMR/EHR system integration",
          "Patient portal with secure login",
          "Telemedicine booking flow",
          "Multi-provider scheduling system",
          "AI chatbot integration",
          "HIPAA compliance review",
          "Heatmap & CRO setup (Hotjar or FullStory)",
          "Custom admin dashboard",
          "Unlimited revisions during build",
          "60-day post-launch support",
          "30-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing SEO from $1,199/mo", "AI Receptionist from $399/mo"],
      },
    ],
    comparison: [
      { feature: "Number of pages", basic: "5 pages", standard: "Up to 12", premium: "Unlimited" },
      { feature: "Custom design", basic: "Template-based", standard: "Custom", premium: "Fully custom + motion" },
      { feature: "Mobile optimization", basic: true, standard: true, premium: true },
      { feature: "Online booking integration", basic: false, standard: true, premium: true },
      { feature: "HIPAA-compliant forms", basic: "Basic forms", standard: "HIPAA-compliant", premium: "HIPAA + patient portal" },
      { feature: "EMR/EHR integration", basic: false, standard: false, premium: true },
      { feature: "PageSpeed score", basic: "70+", standard: "90+", premium: "95+" },
      { feature: "ADA accessibility", basic: false, standard: true, premium: true },
      { feature: "Multi-location support", basic: false, standard: false, premium: true },
      { feature: "AI chatbot", basic: false, standard: false, premium: true },
      { feature: "Post-launch support", basic: "None", standard: "30 days", premium: "60 days" },
      { feature: "Design revisions", basic: "1 round", standard: "3 rounds", premium: "Unlimited" },
    ],
    faqs: [
      { q: "How long does it take to build a healthcare website?", a: "Basic sites deliver in 10 business days, Standard in 21, and Premium in 30. We run a structured sprint — discovery, wireframes, design, development, QA, then launch — with stage updates so you're never in the dark." },
      { q: "Is the website HIPAA compliant?", a: "We don't store PHI directly on the site. All forms and third-party tools are configured to HIPAA-friendly standards. For a signed BAA, we partner with certified hosting providers or work with your compliance team." },
      { q: "Do I own the website after it's built?", a: "100%. You own the code, domain, and every asset. Full repo access is handed off at launch. We never lock you into proprietary platforms." },
      { q: "Can you migrate my existing website?", a: "Yes — content migration and URL redirects are included in Standard and Premium so your existing SEO equity carries over." },
      { q: "What CMS do you use?", a: "We build on Next.js for peak performance and SEO, with Sanity or a headless CMS for easy content updates — no developer needed for routine edits." },
    ],
    timeline: "10–30 business days",
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Sanity CMS", "Vercel", "Firebase"],
    support: "30–60 days post-launch support included based on plan",
    guarantee: "Not happy with the first design round? We redesign it at zero charge.",
  },

  {
    id: "mobile-app",
    name: "Mobile App Development",
    category: "Web & App",
    tagline: "Native-quality healthcare apps that patients actually use — built fast, shipped clean.",
    packages: [
      {
        name: "Basic",
        price: "$5,000",
        period: "one-time",
        description: "A polished single-platform app for practices ready to give patients a branded mobile experience.",
        features: [
          "iOS or Android (single platform)",
          "Up to 8 screens",
          "Appointment request module",
          "Push notification support",
          "Basic user profile (name, DOB, contact)",
          "REST API backend",
          "App Store / Play Store submission",
          "60-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Second platform add-on $4,999", "App maintenance from $149/mo"],
      },
      {
        name: "Standard",
        price: "$15,000",
        period: "one-time",
        savings: "Best value for most practices",
        description: "A dual-platform patient app with real booking, secure messaging, and a health record viewer.",
        features: [
          "iOS + Android (both platforms)",
          "Up to 18 screens",
          "Full appointment booking with calendar sync",
          "Secure in-app patient messaging",
          "Health record & prescription viewer",
          "Push + SMS notifications",
          "Payment integration (Stripe)",
          "Custom branded splash & onboarding",
          "Admin dashboard for staff",
          "90-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Telemedicine module from $4,999", "AI triage chatbot from $2,999"],
      },
      {
        name: "Premium",
        price: "$30,000",
        period: "one-time",
        description: "A full healthcare super-app — iOS, Android, and web — with AI features, telemedicine, and EMR integration.",
        features: [
          "iOS + Android + Progressive Web App",
          "Unlimited screens",
          "Full EMR/EHR integration",
          "Telemedicine video visits",
          "AI symptom checker + triage",
          "Lab results viewer + push alerts",
          "Multi-provider scheduling",
          "Insurance card capture",
          "Biometric authentication",
          "Offline mode support",
          "Custom backend & admin portal",
          "120-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Dedicated post-launch SLA from $599/mo"],
      },
    ],
    comparison: [
      { feature: "Platforms", basic: "iOS or Android", standard: "iOS + Android", premium: "iOS + Android + Web" },
      { feature: "Number of screens", basic: "Up to 8", standard: "Up to 18", premium: "Unlimited" },
      { feature: "Appointment booking", basic: "Request only", standard: "Full booking + calendar sync", premium: "Multi-provider booking" },
      { feature: "Secure patient messaging", basic: false, standard: true, premium: true },
      { feature: "Health records viewer", basic: false, standard: true, premium: true },
      { feature: "EMR/EHR integration", basic: false, standard: false, premium: true },
      { feature: "Telemedicine", basic: false, standard: "Add-on", premium: true },
      { feature: "Payment integration", basic: false, standard: true, premium: true },
      { feature: "AI features", basic: false, standard: false, premium: true },
      { feature: "Admin dashboard", basic: false, standard: true, premium: true },
      { feature: "Delivery time", basic: "60 days", standard: "90 days", premium: "120 days" },
    ],
    faqs: [
      { q: "Do you build native or cross-platform apps?", a: "We use React Native for cross-platform builds that feel fully native — one codebase, two stores, no quality compromise." },
      { q: "How long does App Store approval take?", a: "Apple typically reviews in 1–3 days; Google Play in 1–7 days. We prep all assets and metadata to minimize rejections." },
      { q: "Can the app integrate with our existing EHR?", a: "Yes. Premium includes full EMR/EHR integration. Standard includes a record viewer that connects to most major EHRs via HL7 FHIR API." },
      { q: "Who manages the app after launch?", a: "You own it entirely. We offer maintenance plans from $149/mo for updates, OS compatibility fixes, and ongoing improvements." },
      { q: "Is the patient data HIPAA compliant?", a: "All patient data is encrypted in transit and at rest. We use HIPAA-eligible cloud infrastructure and can work with your compliance officer on a BAA." },
    ],
    timeline: "60–120 business days",
    technologies: ["React Native", "Expo", "Node.js", "Firebase", "PostgreSQL", "Stripe", "Twilio"],
    support: "App Store submission + 30-day bug-fix period included",
    guarantee: "Bug-free launch guarantee — we fix any post-launch defects within 30 days at no charge.",
  },

  {
    id: "custom-software",
    name: "Custom Software Development",
    category: "Web & App",
    tagline: "Purpose-built healthcare software that fits your workflow — not the other way around.",
    packages: [
      {
        name: "Basic",
        price: "$14,999",
        period: "one-time",
        description: "An MVP to validate your product idea with real users — core features, clean UI, fast to market.",
        features: [
          "Up to 5 core features",
          "Web-based SaaS application",
          "Role-based user authentication",
          "Basic admin dashboard",
          "REST API with documentation",
          "PostgreSQL or Firebase database",
          "Hosted on Vercel / AWS",
          "60-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["UI/UX design sprint from $2,999", "Post-MVP support from $149/mo"],
      },
      {
        name: "Standard",
        price: "$29,999",
        period: "one-time",
        savings: "Most chosen by funded startups & growing practices",
        description: "A production-ready product with advanced features, third-party integrations, and a full admin layer.",
        features: [
          "Up to 15 core features",
          "Full web + mobile-responsive application",
          "Advanced RBAC (roles, permissions, audit logs)",
          "Third-party integrations (Stripe, Twilio, EHR APIs)",
          "Real-time notifications",
          "Advanced analytics dashboard",
          "Automated testing suite",
          "CI/CD pipeline setup",
          "90-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Mobile app add-on from $9,999", "Dedicated QA engineer from $2,000"],
      },
      {
        name: "Premium",
        price: "From $59,999",
        period: "one-time",
        description: "Enterprise-grade healthcare software — HIPAA-ready, infinitely scalable, with a dedicated engineering team.",
        features: [
          "Unlimited features — scoped per project",
          "Microservices or monolithic architecture (your choice)",
          "HIPAA-compliant infrastructure with BAA",
          "Multi-tenant SaaS architecture",
          "Advanced AI/ML feature integration",
          "Full FHIR/HL7 compliance",
          "Load-tested to 100k+ concurrent users",
          "Disaster recovery + failover",
          "Dedicated project manager + lead engineer",
          "Custom delivery timeline",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing engineering retainer from $8,000/mo"],
      },
    ],
    comparison: [
      { feature: "Core features", basic: "Up to 5", standard: "Up to 15", premium: "Unlimited" },
      { feature: "Mobile responsive", basic: true, standard: true, premium: true },
      { feature: "User roles & permissions", basic: "Basic", standard: "Advanced RBAC", premium: "Enterprise RBAC + audit logs" },
      { feature: "Third-party integrations", basic: "1–2", standard: "Up to 5", premium: "Unlimited" },
      { feature: "HIPAA compliance", basic: "Best-effort", standard: "HIPAA-ready", premium: "Full HIPAA + BAA" },
      { feature: "FHIR/HL7 support", basic: false, standard: "Partial", premium: "Full" },
      { feature: "Automated testing", basic: false, standard: true, premium: true },
      { feature: "CI/CD pipeline", basic: false, standard: true, premium: true },
      { feature: "Multi-tenancy", basic: false, standard: false, premium: true },
      { feature: "Dedicated team", basic: false, standard: false, premium: true },
      { feature: "Delivery time", basic: "60 days", standard: "90 days", premium: "Custom" },
    ],
    faqs: [
      { q: "How do you handle scope changes mid-project?", a: "We use agile sprints with biweekly reviews. Minor changes are absorbed; significant scope additions are quoted separately so there are no billing surprises." },
      { q: "Who owns the code?", a: "You do — 100%. Full IP transfer, source code, and deployment credentials are handed over at project close." },
      { q: "Can you build HIPAA-compliant software?", a: "Yes. Our Standard and Premium builds run on HIPAA-eligible cloud infrastructure (AWS or Azure). We configure encryption, access controls, and audit logging, and can sign a BAA." },
      { q: "Do you have healthcare industry experience?", a: "Yes — we've built patient portals, scheduling systems, billing tools, and EHR integrations for dental, aesthetic, and multi-specialty groups." },
      { q: "What happens after launch?", a: "We include a 30-day bug-fix period on all plans. After that, we offer retainer support for ongoing development." },
    ],
    timeline: "60–120+ business days depending on scope",
    technologies: ["Next.js", "Node.js", "PostgreSQL", "Redis", "AWS", "Docker", "TypeScript", "React"],
    support: "30-day post-launch bug-fix period included on all plans",
    guarantee: "If we miss agreed milestones without cause, we credit your next invoice.",
  },

  {
    id: "ui-ux-design",
    name: "UI/UX Design",
    category: "Web & App",
    tagline: "Interfaces that patients trust and staff actually enjoy using — designed with clinical workflows in mind.",
    packages: [
      {
        name: "Basic",
        price: "$2,999",
        period: "one-time",
        description: "High-fidelity mockups for a focused product — perfect before handing off to development.",
        features: [
          "Up to 8 screens / key views",
          "Desktop + mobile breakpoints",
          "Wireframing + mockup",
          "Brand color & typography applied",
          "Component library (Figma)",
          "1 round of revisions",
          "Developer-ready Figma handoff",
          "10-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Additional screens at $150/screen"],
      },
      {
        name: "Standard",
        price: "$5,999",
        period: "one-time",
        savings: "Ideal for web apps and patient portals",
        description: "A complete, interactive prototype backed by user research — ready for dev and investor demos.",
        features: [
          "Up to 20 screens across all user flows",
          "User research & competitor analysis",
          "Information architecture mapping",
          "Wireframes → high-fidelity mockups",
          "Interactive Figma prototype (clickable)",
          "Design system: colors, type, icons, spacing",
          "Accessibility audit (WCAG 2.1 AA)",
          "3 rounds of revisions",
          "Annotated developer handoff",
          "21-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Usability testing sessions from $499", "Motion design from $799"],
      },
      {
        name: "Premium",
        price: "$11,999",
        period: "one-time",
        description: "A full product design system — from brand identity through every screen, animation, and component.",
        features: [
          "Unlimited screens",
          "Full UX research sprint (interviews, user journey maps)",
          "Multi-role user flows (patient, provider, admin)",
          "Complete design system + component library",
          "Motion & micro-interaction design",
          "Usability testing with 5 real users",
          "A/B testing ready variants",
          "WCAG 2.1 AA accessibility compliance",
          "Storybook documentation",
          "Unlimited revisions during project",
          "30-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing design retainer from $2,999/mo"],
      },
    ],
    comparison: [
      { feature: "Number of screens", basic: "Up to 8", standard: "Up to 20", premium: "Unlimited" },
      { feature: "User research", basic: false, standard: true, premium: "Full research sprint" },
      { feature: "Interactive prototype", basic: false, standard: true, premium: true },
      { feature: "Design system", basic: "Basic components", standard: "Full design system", premium: "Complete + Storybook" },
      { feature: "Motion design", basic: false, standard: "Add-on", premium: true },
      { feature: "Accessibility audit", basic: false, standard: "WCAG 2.1 AA", premium: "WCAG 2.1 AA + report" },
      { feature: "Usability testing", basic: false, standard: "Add-on", premium: "5 real users" },
      { feature: "Design revisions", basic: "1 round", standard: "3 rounds", premium: "Unlimited" },
      { feature: "Dev handoff (Figma)", basic: true, standard: "Annotated", premium: "Annotated + Storybook" },
      { feature: "Delivery time", basic: "10 days", standard: "21 days", premium: "30 days" },
    ],
    faqs: [
      { q: "Do you design for both web and mobile?", a: "Yes. All plans include desktop and mobile breakpoints. Premium includes all device sizes and native app screens." },
      { q: "What tools do you use?", a: "Figma for all design and prototyping. We deliver dev-ready handoff files with assets exported and spacing annotated." },
      { q: "Can you work with our existing brand?", a: "Absolutely. We work within your existing brand guidelines or build a new visual identity alongside the UX work." },
      { q: "Will the designs be developer-ready?", a: "Yes. Every plan delivers Figma files with organized layers, reusable components, and export-ready assets. Standard and Premium include detailed annotations." },
      { q: "Can you design for HIPAA-sensitive data views?", a: "Yes — we've designed patient portals, EHR dashboards, and clinical workflows with HIPAA data visibility best practices in mind." },
    ],
    timeline: "10–30 business days",
    technologies: ["Figma", "FigJam", "Protopie", "Storybook", "WCAG 2.1 guidelines"],
    support: "Dedicated Slack channel during active project",
    guarantee: "First round of designs not what you envisioned? We redo it — no charge.",
  },

  // ─── AI & AUTOMATION ────────────────────────────────────────────────────────
  {
    id: "ai-receptionist",
    name: "AI Receptionist",
    category: "AI & Automation",
    tagline: "Answers every call, books every patient — 24/7, with zero hold time.",
    packages: [
      {
        name: "Basic",
        price: "$399",
        period: "/ month",
        description: "An always-on AI voice receptionist for smaller practices ready to stop missing calls after hours.",
        features: [
          "Up to 300 inbound calls / month",
          "English-language voice AI",
          "Appointment request capture",
          "Basic FAQ handling (hours, location, pricing)",
          "Voicemail transcription to email",
          "Call summary report (monthly)",
          "5-business-day setup",
        ],
        cta: "Start Free Trial",
        popular: false,
        addOns: ["Spanish language support +$99/mo", "SMS follow-up module +$79/mo"],
      },
      {
        name: "Standard",
        price: "$799",
        period: "/ month",
        savings: "Save $2,400/yr vs. a part-time receptionist",
        description: "A fully autonomous receptionist that books, confirms, and follows up — without any staff involvement.",
        features: [
          "Up to 800 inbound calls / month",
          "English + Spanish voice AI",
          "Live calendar booking (Google, iCal, or custom)",
          "Advanced FAQ training on your services & fees",
          "No-show SMS + WhatsApp reminders",
          "Call recording & searchable transcripts",
          "Weekly performance dashboard",
          "CRM data sync (HubSpot, Salesforce, or Zoho)",
          "3-business-day setup",
        ],
        cta: "Start Free Trial",
        popular: true,
        addOns: ["Additional 500 calls block +$149/mo", "EHR booking sync +$199/mo"],
      },
      {
        name: "Premium",
        price: "$1,499",
        period: "/ month",
        description: "Unlimited calls, custom branded voice, full EMR integration — the enterprise tier for high-volume practices.",
        features: [
          "Unlimited inbound calls",
          "Custom branded voice persona",
          "Multi-language (English, Spanish, + custom)",
          "Direct EMR/EHR appointment booking",
          "Intelligent patient routing (new vs. returning)",
          "After-hours emergency escalation",
          "Real-time call monitoring dashboard",
          "Predictive no-show risk alerts",
          "Weekly strategy call with your success manager",
          "Same-day setup + dedicated onboarding",
        ],
        cta: "Book a Demo",
        popular: false,
        addOns: ["Outbound recall campaigns +$299/mo"],
      },
    ],
    comparison: [
      { feature: "Monthly call volume", basic: "300 calls", standard: "800 calls", premium: "Unlimited" },
      { feature: "Languages", basic: "English", standard: "English + Spanish", premium: "Multi-language + custom" },
      { feature: "Live calendar booking", basic: false, standard: true, premium: true },
      { feature: "SMS/WhatsApp reminders", basic: false, standard: true, premium: true },
      { feature: "Call recordings & transcripts", basic: false, standard: true, premium: true },
      { feature: "CRM sync", basic: false, standard: true, premium: true },
      { feature: "EMR/EHR booking sync", basic: false, standard: "Add-on", premium: true },
      { feature: "Custom branded voice", basic: false, standard: false, premium: true },
      { feature: "Real-time dashboard", basic: "Monthly report", standard: "Weekly dashboard", premium: "Real-time + alerts" },
      { feature: "Emergency escalation", basic: false, standard: false, premium: true },
      { feature: "Setup time", basic: "5 days", standard: "3 days", premium: "Same day" },
    ],
    faqs: [
      { q: "How does the AI handle complex or sensitive patient questions?", a: "It handles common questions autonomously and escalates complex or clinical queries to your human staff in real time via SMS or a warm transfer — no patient left without an answer." },
      { q: "Is it HIPAA compliant?", a: "Yes. Call recordings are stored on HIPAA-eligible infrastructure, encrypted at rest and in transit. We sign a BAA on request." },
      { q: "Can it use our existing phone number?", a: "Yes. We port your current clinic number or provision a new dedicated line — whichever you prefer." },
      { q: "What happens if a patient calls while the AI is handling another call?", a: "The AI handles unlimited simultaneous calls on Standard and Premium. No busy signals, no hold queues." },
      { q: "How quickly can we go live?", a: "Basic: 5 business days. Standard: 3 days. Premium: same day. We train the AI on your services, pricing, and FAQs before going live." },
    ],
    timeline: "1–5 business days to go live",
    technologies: ["Vapi.ai", "OpenAI GPT-4", "Twilio", "Google Calendar API", "Firebase", "Deepgram"],
    support: "24/7 uptime monitoring. Premium includes a dedicated success manager.",
    guarantee: "30-day performance guarantee — if the AI mishandles calls in week 1, we retrain it free of charge.",
  },

  {
    id: "ai-chatbots",
    name: "AI Chatbots",
    category: "AI & Automation",
    tagline: "Intelligent patient-facing chatbots that answer, qualify, and book — across every channel.",
    packages: [
      {
        name: "Basic",
        price: "$299",
        period: "/ month",
        description: "A single website chatbot that captures leads and answers patient FAQs around the clock.",
        features: [
          "1 chatbot deployment (website)",
          "500 conversations / month",
          "Pre-built healthcare FAQ templates",
          "Lead capture (name, email, phone, concern)",
          "Email notification for new leads",
          "Customizable chat widget branding",
          "7-day setup",
        ],
        cta: "Start Free Trial",
        popular: false,
        addOns: ["WhatsApp channel add-on +$99/mo", "Facebook Messenger add-on +$79/mo"],
      },
      {
        name: "Standard",
        price: "$599",
        period: "/ month",
        savings: "3× more channels, 4× more conversations",
        description: "An omni-channel AI chatbot that books appointments, syncs to your CRM, and hands off to humans seamlessly.",
        features: [
          "3 chatbot deployments (website + WhatsApp + Facebook)",
          "2,000 conversations / month",
          "Custom AI training on your services & FAQs",
          "Live appointment booking integration",
          "Human handoff with full chat context",
          "CRM sync (HubSpot, Zoho, or Salesforce)",
          "Conversation analytics dashboard",
          "Multilingual support (10 languages)",
          "5-day setup",
        ],
        cta: "Start Free Trial",
        popular: true,
        addOns: ["Additional 1,000 conversations +$99/mo", "Custom AI persona +$299 one-time"],
      },
      {
        name: "Premium",
        price: "$1,199",
        period: "/ month",
        description: "Unlimited chatbots across every channel — with deep AI training, A/B testing, and enterprise analytics.",
        features: [
          "Unlimited chatbot deployments",
          "Unlimited conversations",
          "Proprietary AI training on your clinical content",
          "EMR-connected appointment booking",
          "Conversation sentiment analysis",
          "A/B testing for conversion optimization",
          "Advanced analytics + revenue attribution",
          "HIPAA-compliant conversation storage",
          "Dedicated AI trainer + monthly tuning",
          "3-day setup",
        ],
        cta: "Book a Demo",
        popular: false,
        addOns: ["AI voice bot integration from $399/mo"],
      },
    ],
    comparison: [
      { feature: "Number of chatbots", basic: "1", standard: "3", premium: "Unlimited" },
      { feature: "Monthly conversations", basic: "500", standard: "2,000", premium: "Unlimited" },
      { feature: "Deployment channels", basic: "Website only", standard: "Website + WhatsApp + Facebook", premium: "All channels" },
      { feature: "Appointment booking", basic: false, standard: true, premium: true },
      { feature: "Custom AI training", basic: "Templates", standard: "Custom training", premium: "Deep clinical training" },
      { feature: "Human handoff", basic: false, standard: true, premium: true },
      { feature: "CRM sync", basic: false, standard: true, premium: true },
      { feature: "EMR integration", basic: false, standard: false, premium: true },
      { feature: "Multilingual", basic: false, standard: "10 languages", premium: "Unlimited languages" },
      { feature: "A/B testing", basic: false, standard: false, premium: true },
      { feature: "HIPAA storage", basic: false, standard: false, premium: true },
      { feature: "Setup time", basic: "7 days", standard: "5 days", premium: "3 days" },
    ],
    faqs: [
      { q: "How is the chatbot trained on my practice's information?", a: "We ingest your website content, service list, pricing, FAQs, and any intake documents. The AI learns your practice specifically — not generic medical content." },
      { q: "Can it book directly into our scheduling system?", a: "Standard and Premium include live booking integrations with Calendly, Jane App, Kareo, or custom scheduling systems via API." },
      { q: "What happens when the AI can't answer?", a: "It escalates gracefully to a human with full conversation context — no patient has to repeat themselves." },
      { q: "Is patient data stored securely?", a: "Standard conversations are anonymized in analytics. Premium includes HIPAA-compliant encrypted storage for full conversation history." },
      { q: "Can we customize how the chatbot looks and sounds?", a: "Yes — brand colors, avatar, name, and personality are all customizable on every plan. Premium includes a fully custom AI persona." },
    ],
    timeline: "3–7 business days to go live",
    technologies: ["OpenAI GPT-4o", "LangChain", "Voiceflow", "Twilio", "HubSpot API", "Firebase"],
    support: "Uptime monitoring + monthly performance review included",
    guarantee: "14-day free trial on Basic and Standard — no card required.",
  },

  {
    id: "whatsapp-automation",
    name: "WhatsApp AI Automation",
    category: "AI & Automation",
    tagline: "Turn your WhatsApp number into a 24/7 patient engagement engine.",
    packages: [
      {
        name: "Basic",
        price: "$249",
        period: "/ month",
        description: "Automated appointment reminders and instant replies — stop losing patients to unanswered WhatsApp messages.",
        features: [
          "500 outbound messages / month",
          "Automated appointment reminders",
          "Instant auto-reply for common questions",
          "2 pre-built conversation flows",
          "Business hours configuration",
          "Monthly delivery report",
          "5-day setup",
        ],
        cta: "Get Started",
        popular: false,
        addOns: ["Additional 500 messages +$49/mo", "Broadcast campaigns +$99/mo"],
      },
      {
        name: "Standard",
        price: "$499",
        period: "/ month",
        savings: "Most practices recoup the cost in 2 recovered bookings",
        description: "A full patient journey on WhatsApp — from first inquiry through confirmed booking and post-visit follow-up.",
        features: [
          "2,500 outbound messages / month",
          "AI-powered instant replies (NLP)",
          "Full appointment booking flow",
          "Automated pre- and post-visit sequences",
          "8 custom conversation flows",
          "Broadcast campaigns (promotions, recalls)",
          "Read receipt & engagement tracking",
          "CRM lead sync",
          "Conversation analytics dashboard",
          "3-day setup",
        ],
        cta: "Get Started",
        popular: true,
        addOns: ["Additional flows +$99 each", "Multi-agent inbox +$149/mo"],
      },
      {
        name: "Premium",
        price: "$999",
        period: "/ month",
        description: "Unlimited messaging, AI-driven conversations, EMR sync, and broadcast campaigns — the full WhatsApp automation stack.",
        features: [
          "Unlimited outbound messages",
          "Advanced NLP AI replies",
          "Unlimited conversation flows",
          "EMR/EHR appointment sync",
          "Multi-agent team inbox with routing",
          "Broadcast campaigns with segmentation",
          "No-show recovery sequences",
          "Review generation flows (Google, Healthgrades)",
          "Real-time conversation analytics",
          "Dedicated onboarding + monthly strategy call",
        ],
        cta: "Book a Demo",
        popular: false,
        addOns: ["AI voice escalation from $299/mo"],
      },
    ],
    comparison: [
      { feature: "Monthly messages", basic: "500", standard: "2,500", premium: "Unlimited" },
      { feature: "AI-powered replies", basic: false, standard: true, premium: true },
      { feature: "Appointment booking flow", basic: false, standard: true, premium: true },
      { feature: "Custom conversation flows", basic: "2 flows", standard: "8 flows", premium: "Unlimited" },
      { feature: "Broadcast campaigns", basic: "Add-on", standard: true, premium: "With segmentation" },
      { feature: "EMR/EHR sync", basic: false, standard: false, premium: true },
      { feature: "Multi-agent inbox", basic: false, standard: "Add-on", premium: true },
      { feature: "Review generation", basic: false, standard: false, premium: true },
      { feature: "No-show recovery", basic: "Basic reminders", standard: "Reminder sequences", premium: "Full recovery flows" },
      { feature: "CRM sync", basic: false, standard: true, premium: true },
      { feature: "Analytics", basic: "Monthly report", standard: "Dashboard", premium: "Real-time + AI insights" },
      { feature: "Setup time", basic: "5 days", standard: "3 days", premium: "2 days" },
    ],
    faqs: [
      { q: "Do you use the official WhatsApp Business API?", a: "Yes — we integrate through Meta's official Business API, which means no risk of your number being banned and full broadcast capability." },
      { q: "Can patients book appointments directly in WhatsApp?", a: "Yes on Standard and Premium. The AI guides them through a natural-language booking flow, checks availability, confirms, and sends a calendar invite." },
      { q: "Is patient data safe over WhatsApp?", a: "WhatsApp uses end-to-end encryption for messages. We don't store PHI beyond what's needed for booking sync, and comply with HIPAA data handling principles." },
      { q: "Can I still reply to patients manually?", a: "Absolutely. The AI handles routine messages automatically. You — or your team — can jump into any conversation at any time via the team inbox." },
      { q: "What's the difference between this and a chatbot?", a: "WhatsApp automation lives on a channel patients already use daily, with higher open rates (98% vs. email's ~20%). The AI is trained on your specific practice, not generic responses." },
    ],
    timeline: "2–5 business days to go live",
    technologies: ["WhatsApp Business API", "Meta Cloud API", "OpenAI", "Twilio", "Zapier", "Firebase"],
    support: "Uptime monitoring + message delivery guarantee included",
    guarantee: "If your message delivery rate falls below 95% for any reason, we issue a service credit.",
  },

  {
    id: "ai-workflow",
    name: "AI Workflow Automation",
    category: "AI & Automation",
    tagline: "Replace repetitive manual tasks with AI agents that work around the clock.",
    packages: [
      {
        name: "Basic",
        price: "$1,499",
        period: "/ month",
        description: "Automate your top 3 highest-volume manual workflows — eliminate the busywork your team hates most.",
        features: [
          "3 automated workflows",
          "5,000 automated tasks / month",
          "Email-based trigger automation",
          "Basic data extraction & routing",
          "Google Workspace integration",
          "Monthly performance report",
          "7-day build time",
        ],
        cta: "Get Started",
        popular: false,
        addOns: ["Additional workflow +$299/mo each"],
      },
      {
        name: "Standard",
        price: "$2,999",
        period: "/ month",
        savings: "Saves the equivalent of 2 full-time admin roles",
        description: "10 interconnected workflows across your core business systems — from intake to billing to follow-up.",
        features: [
          "10 automated workflows",
          "25,000 automated tasks / month",
          "Multi-system integration (EHR, CRM, billing)",
          "AI document processing & data extraction",
          "Conditional logic & branching",
          "Real-time error alerts",
          "Workflow monitoring dashboard",
          "Quarterly workflow audit & optimization",
          "5-day build time",
        ],
        cta: "Get Started",
        popular: true,
        addOns: ["Custom AI model training +$1,499 one-time", "Slack / Teams alerts +$99/mo"],
      },
      {
        name: "Premium",
        price: "$5,999",
        period: "/ month",
        description: "Unlimited AI agents running your entire operations — intake, billing, compliance, communications, and beyond.",
        features: [
          "Unlimited automated workflows",
          "Unlimited tasks / month",
          "Enterprise system integrations",
          "Custom AI model fine-tuning",
          "AI-driven decision logic",
          "Full process mining & bottleneck detection",
          "Real-time monitoring + anomaly detection",
          "Dedicated automation engineer",
          "Weekly strategy session",
          "3-day build time for new workflows",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Custom AI agent development from $4,999 one-time"],
      },
    ],
    comparison: [
      { feature: "Automated workflows", basic: "3", standard: "10", premium: "Unlimited" },
      { feature: "Tasks / month", basic: "5,000", standard: "25,000", premium: "Unlimited" },
      { feature: "Multi-system integration", basic: "Limited", standard: true, premium: "Enterprise-grade" },
      { feature: "AI document processing", basic: false, standard: true, premium: true },
      { feature: "Conditional logic", basic: false, standard: true, premium: true },
      { feature: "Custom AI model", basic: false, standard: "Add-on", premium: true },
      { feature: "Monitoring dashboard", basic: "Monthly report", standard: true, premium: "Real-time + alerts" },
      { feature: "Dedicated engineer", basic: false, standard: false, premium: true },
      { feature: "Process mining", basic: false, standard: false, premium: true },
      { feature: "Build time", basic: "7 days", standard: "5 days", premium: "3 days" },
    ],
    faqs: [
      { q: "What kinds of workflows can you automate?", a: "Patient intake processing, insurance eligibility checks, appointment reminders, billing follow-ups, referral routing, lab result notifications, review requests, and more. If a human does it on a screen, we can automate it." },
      { q: "Do we need to change our existing software?", a: "No. We integrate with your current stack via APIs and automation platforms — no rip-and-replace required." },
      { q: "How long does it take to see results?", a: "Most clients see measurable time savings within the first 2 weeks. We prioritize your highest-volume pain points first." },
      { q: "What if a workflow breaks?", a: "Real-time error alerts notify your team instantly. Standard and Premium include a 4-hour response SLA for critical workflow failures." },
      { q: "Can the AI make decisions, or does a human always approve?", a: "Both. We configure approval gates where needed and let the AI act fully autonomously where it's safe to do so — your choice per workflow." },
    ],
    timeline: "3–7 business days per workflow batch",
    technologies: ["n8n", "Make (Integromat)", "OpenAI", "LangChain", "Zapier", "Python", "Firebase Functions"],
    support: "Uptime monitoring + error alerting included on all plans",
    guarantee: "If we can't automate an agreed workflow, we refund that workflow's setup cost.",
  },

  // ─── MARKETING ──────────────────────────────────────────────────────────────
  {
    id: "local-seo",
    name: "Local SEO",
    category: "Marketing",
    tagline: "Rank first when patients search 'dentist near me' — dominate your local market.",
    packages: [
      {
        name: "Basic",
        price: "$300",
        period: "/ month",
        description: "A strong local SEO foundation for single-location practices ready to start appearing in Google's local pack.",
        features: [
          "1 location optimized",
          "10 target local keywords",
          "Google Business Profile optimization",
          "Monthly citation building (10 directories)",
          "NAP consistency audit & fix",
          "Review monitoring alerts",
          "Geo-targeted on-page optimization",
          "Monthly ranking report",
        ],
        cta: "Start Growing",
        popular: false,
        addOns: ["Additional location +$199/mo", "Review generation campaign +$149/mo"],
      },
      {
        name: "Standard",
        price: "$500",
        period: "/ month",
        savings: "Average client sees local pack ranking in 60–90 days",
        description: "An aggressive local presence strategy for multi-location practices ready to own their ZIP code.",
        features: [
          "Up to 3 locations optimized",
          "25 target local keywords",
          "Full Google Business Profile management",
          "Monthly citation building (25 directories)",
          "Local link building (5 links/mo)",
          "Review generation system",
          "Competitor ranking tracking",
          "Hyperlocal content updates (2/mo)",
          "Bi-weekly ranking report",
          "Monthly strategy call",
        ],
        cta: "Start Growing",
        popular: true,
        addOns: ["4th+ location at $199/mo each", "Google Ads synergy package +$499/mo"],
      },
      {
        name: "Premium",
        price: "$700",
        period: "/ month",
        description: "Total local market domination — 5+ locations, aggressive link building, and review management at scale.",
        features: [
          "Up to 5 locations (additional +$149/mo each)",
          "50+ target local keywords",
          "Full GBP management with weekly posts",
          "Citation building (50 directories/mo)",
          "Local PR + link building (15 links/mo)",
          "Automated review generation system",
          "Review response management",
          "Local competitor conquesting",
          "Weekly ranking dashboard",
          "Dedicated local SEO strategist",
          "Weekly check-in call",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["National SEO expansion from $599/mo add-on"],
      },
    ],
    comparison: [
      { feature: "Locations", basic: "1", standard: "Up to 3", premium: "Up to 5" },
      { feature: "Target keywords", basic: "10", standard: "25", premium: "50+" },
      { feature: "GBP management", basic: "Setup only", standard: "Full management", premium: "Full + weekly posts" },
      { feature: "Monthly citations", basic: "10 directories", standard: "25 directories", premium: "50 directories" },
      { feature: "Local link building", basic: false, standard: "5 links/mo", premium: "15 links/mo" },
      { feature: "Review generation", basic: "Monitoring only", standard: true, premium: "Automated + responses" },
      { feature: "Competitor tracking", basic: false, standard: true, premium: "Conquesting strategy" },
      { feature: "Local content", basic: false, standard: "2 updates/mo", premium: "Weekly GBP posts" },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Strategy calls", basic: false, standard: "Monthly", premium: "Weekly" },
      { feature: "Dedicated strategist", basic: false, standard: false, premium: true },
    ],
    faqs: [
      { q: "How long does local SEO take to show results?", a: "Most practices see movement in the local 3-pack within 60–90 days. Competitive markets may take 90–120 days. Unlike ads, local SEO results compound over time." },
      { q: "What is Google Business Profile optimization?", a: "We optimize every field — categories, services, attributes, photos, Q&A, and regular posts — to maximize your relevance score in Google's local algorithm." },
      { q: "What's the difference between Local SEO and regular SEO?", a: "Local SEO targets 'near me' searches and the Google Maps 3-pack. Regular SEO targets broader informational keywords. For practices, Local SEO typically delivers faster patient ROI." },
      { q: "Do you manage our Google reviews?", a: "Standard and Premium include review generation (automated asks post-visit) and monitoring. Premium adds professional response management to every review." },
      { q: "Can you help multiple office locations?", a: "Yes — Standard covers up to 3 locations and Premium up to 5, each with independent GBP management, citations, and location-specific keyword targeting." },
    ],
    timeline: "Results typically visible in 60–90 days",
    technologies: ["Google Business Profile", "BrightLocal", "Ahrefs", "Moz Local", "SEMrush", "Google Search Console"],
    support: "Monthly report + dedicated account manager on Standard and Premium",
    guarantee: "If we don't improve your local ranking by month 3, you get month 4 free.",
  },

  {
    id: "seo",
    name: "SEO",
    category: "Marketing",
    tagline: "Long-term organic visibility that compounds — ranking for the keywords your patients actually search.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month",
        description: "On-page SEO and technical foundations for practices ready to start earning organic traffic.",
        features: [
          "10 pages optimized / month",
          "15 target keywords",
          "Full technical SEO audit",
          "On-page optimization (titles, H-tags, meta, schema)",
          "XML sitemap + robots.txt management",
          "Monthly keyword movement report",
          "Core Web Vitals monitoring",
        ],
        cta: "Start Growing",
        popular: false,
        addOns: ["Blog content 2 posts/mo +$299", "Link building starter +$299/mo"],
      },
      {
        name: "Standard",
        price: "$700",
        period: "/ month",
        savings: "Average 4× ROI within 6 months for healthcare clients",
        description: "Full-spectrum SEO with content creation, link building, and competitor displacement.",
        features: [
          "25 pages optimized / month",
          "35 target keywords",
          "Technical SEO (crawl errors, page speed, structured data)",
          "4 SEO-optimized blog posts / month",
          "Link building (5 DR40+ backlinks / month)",
          "Competitor gap analysis",
          "Google Search Console management",
          "Bi-weekly ranking report",
          "Monthly strategy call",
        ],
        cta: "Start Growing",
        popular: true,
        addOns: ["Additional 5 links/mo +$399", "Local SEO package +$499/mo"],
      },
      {
        name: "Premium",
        price: "$1,000",
        period: "/ month",
        description: "Aggressive, authority-building SEO for practices ready to own page 1 for their entire service menu.",
        features: [
          "50+ pages optimized / month",
          "75+ target keywords",
          "Full technical SEO including JS rendering",
          "8 SEO blog posts + 2 pillar pages / month",
          "Link building (15 DR50+ links / month)",
          "Digital PR campaigns",
          "Featured snippet targeting",
          "Topical authority mapping",
          "Schema markup for all content types",
          "Weekly ranking dashboard",
          "Dedicated SEO strategist",
          "Weekly check-in",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Paid ads integration from $499/mo"],
      },
    ],
    comparison: [
      { feature: "Pages optimized / month", basic: "10", standard: "25", premium: "50+" },
      { feature: "Target keywords", basic: "15", standard: "35", premium: "75+" },
      { feature: "Technical SEO", basic: "Audit only", standard: "Ongoing", premium: "Full + JS rendering" },
      { feature: "Blog content / month", basic: "None", standard: "4 posts", premium: "8 posts + 2 pillar pages" },
      { feature: "Link building / month", basic: "None", standard: "5 DR40+ links", premium: "15 DR50+ links" },
      { feature: "Digital PR", basic: false, standard: false, premium: true },
      { feature: "Competitor gap analysis", basic: false, standard: true, premium: "Ongoing" },
      { feature: "Schema markup", basic: "Basic", standard: "Full", premium: "All content types" },
      { feature: "Featured snippet targeting", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Dedicated strategist", basic: false, standard: false, premium: true },
    ],
    faqs: [
      { q: "How long does it take to rank on Google?", a: "For competitive healthcare keywords, typically 3–6 months of consistent work. Less competitive terms often rank in 4–8 weeks. Unlike paid ads, organic rankings continue delivering results after the campaign ends." },
      { q: "Do you create the content or do we?", a: "On Standard and Premium, we handle all content creation — researched, clinician-reviewed, and optimized for ranking and patient conversion." },
      { q: "What's your link building approach?", a: "We earn links through digital PR, guest posts on medical and health publications, and relationship-based outreach — never spammy link farms." },
      { q: "How do you measure success?", a: "Keyword rankings, organic traffic, new patient inquiries from organic, and conversion rate from organic landing pages — all tracked in your reporting dashboard." },
      { q: "Can SEO work alongside our paid ads?", a: "Absolutely — SEO and paid ads complement each other. SEO covers long-term organic growth while ads drive immediate traffic. We offer a synergy package when combining both." },
    ],
    timeline: "First ranking movements typically in 60–90 days",
    technologies: ["Ahrefs", "SEMrush", "Google Search Console", "Screaming Frog", "Surfer SEO", "Google Analytics 4"],
    support: "Monthly reporting + account manager included on all plans",
    guarantee: "If your organic traffic doesn't increase in 90 days, we work for free until it does.",
  },

  {
    id: "google-ads",
    name: "Google Ads Management",
    category: "Marketing",
    tagline: "Paid search that puts your practice in front of patients searching for exactly what you offer — right now.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month + ad spend",
        description: "Managed Google Search campaigns for practices ready to start generating patient leads from paid traffic.",
        features: [
          "1 Google Search campaign",
          "Manage up to $3,000 ad spend / month",
          "Keyword research & negative keyword setup",
          "Ad copywriting (3 ads per ad group)",
          "Conversion tracking setup",
          "Monthly optimization review",
          "Monthly performance report",
        ],
        cta: "Launch Campaigns",
        popular: false,
        addOns: ["Display/retargeting campaign +$149/mo", "Landing page design +$499 one-time"],
      },
      {
        name: "Standard",
        price: "$900",
        period: "/ month + ad spend",
        savings: "Average 4× ROAS for healthcare practices",
        description: "Multi-campaign Google Ads management with A/B testing and conversion rate optimization.",
        features: [
          "Up to 3 campaigns (Search + Display + Retargeting)",
          "Manage up to $10,000 ad spend / month",
          "Advanced keyword segmentation",
          "Weekly bid strategy optimization",
          "A/B ad copy testing",
          "Advanced conversion tracking (calls, forms, bookings)",
          "Audience & demographic targeting",
          "Competitor conquest campaigns",
          "Bi-weekly performance report",
          "Monthly strategy call",
        ],
        cta: "Launch Campaigns",
        popular: true,
        addOns: ["YouTube ads campaign +$299/mo", "Custom landing page +$799 one-time"],
      },
      {
        name: "Premium",
        price: "$1,400",
        period: "/ month + ad spend",
        description: "Full-funnel Google Ads ecosystem — search, display, YouTube, and Performance Max — with daily optimization.",
        features: [
          "Unlimited campaigns",
          "Unlimited ad spend management",
          "Search + Display + YouTube + Performance Max",
          "Daily bid adjustment & optimization",
          "Smart bidding with custom conversion values",
          "Custom landing pages per campaign",
          "Call tracking with call recording",
          "CRM integration for offline conversion import",
          "Competitive intelligence reporting",
          "Weekly dashboard + dedicated ads manager",
          "Weekly check-in call",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Meta Ads bundle at $1,499/mo (save $500)"],
      },
    ],
    comparison: [
      { feature: "Campaigns managed", basic: "1 Search", standard: "Search + Display + Retargeting", premium: "Unlimited (all types)" },
      { feature: "Monthly ad spend cap", basic: "Up to $3,000", standard: "Up to $10,000", premium: "Unlimited" },
      { feature: "Bid optimization", basic: "Monthly", standard: "Weekly", premium: "Daily" },
      { feature: "A/B ad testing", basic: false, standard: true, premium: true },
      { feature: "Call tracking", basic: "Basic", standard: "Advanced", premium: "Recording + transcripts" },
      { feature: "Custom landing pages", basic: "Not included", standard: "Add-on", premium: "Included" },
      { feature: "YouTube ads", basic: false, standard: "Add-on", premium: true },
      { feature: "Performance Max", basic: false, standard: false, premium: true },
      { feature: "CRM conversion import", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
      { feature: "Strategy calls", basic: false, standard: "Monthly", premium: "Weekly" },
    ],
    faqs: [
      { q: "What ad spend budget do I need?", a: "We recommend a minimum of $1,500/mo in ad spend for meaningful results in healthcare. Competitive markets (dental implants, cosmetic surgery) typically need $3,000–$10,000/mo to see significant volume." },
      { q: "How quickly will I see patient leads?", a: "Google Ads can generate leads within 48–72 hours of launch. Expect the first 2 weeks to be an optimization period as the algorithm learns." },
      { q: "Is your management fee separate from ad spend?", a: "Yes — our management fee is separate from the budget you pay directly to Google. You always have full visibility into both." },
      { q: "Do you build the landing pages?", a: "Standard includes landing page recommendations; Premium includes custom landing pages. We can also build dedicated pages as an add-on for Basic clients." },
      { q: "What makes healthcare Google Ads different?", a: "Healthcare ads require careful compliance with Google's healthcare policies, especially for sensitive categories. We know these policies well and ensure your campaigns stay live and compliant." },
    ],
    timeline: "Campaigns live within 3–5 business days",
    technologies: ["Google Ads", "Google Analytics 4", "Google Tag Manager", "CallRail", "HubSpot", "Looker Studio"],
    support: "Account manager + performance reporting included on all plans",
    guarantee: "If we don't improve your cost-per-lead vs. your previous campaigns within 60 days, we refund one month of management.",
  },

  {
    id: "meta-ads",
    name: "Meta Ads Management",
    category: "Marketing",
    tagline: "Facebook & Instagram ads that build patient awareness, drive bookings, and grow your practice's revenue.",
    packages: [
      {
        name: "Basic",
        price: "$500",
        period: "/ month + ad spend",
        description: "Foundational Meta advertising for practices ready to reach patients on Facebook and Instagram.",
        features: [
          "2 ad sets (Facebook + Instagram)",
          "Manage up to $3,000 ad spend / month",
          "Core audience targeting setup",
          "Static image + copy creative",
          "Facebook Pixel installation",
          "Monthly campaign optimization",
          "Monthly performance report",
        ],
        cta: "Launch Campaigns",
        popular: false,
        addOns: ["Video ad creative +$399 one-time", "Retargeting setup +$149/mo"],
      },
      {
        name: "Standard",
        price: "$1,000",
        period: "/ month + ad spend",
        savings: "Custom audiences drive 60% lower CPL on average",
        description: "Full-funnel Meta campaigns with lookalike audiences, A/B testing, and creative that converts.",
        features: [
          "5 ad sets across Facebook, Instagram & Messenger",
          "Manage up to $10,000 ad spend / month",
          "Custom audience + lookalike targeting",
          "Carousel + video + story ad formats",
          "A/B creative testing",
          "Retargeting sequences",
          "Lead form ads setup",
          "Weekly bid optimization",
          "Bi-weekly performance report",
          "Monthly strategy call",
        ],
        cta: "Launch Campaigns",
        popular: true,
        addOns: ["Monthly creative refresh +$299", "Influencer coordination +$499/mo"],
      },
      {
        name: "Premium",
        price: "$1,500",
        period: "/ month + ad spend",
        description: "Full-funnel Meta advertising — from cold audience awareness to booked appointments — with daily management.",
        features: [
          "Unlimited ad sets",
          "Unlimited ad spend management",
          "Full funnel (awareness → consideration → conversion)",
          "Advanced Advantage+ AI campaigns",
          "Dynamic ad personalization",
          "Customer list suppression & lookalikes",
          "Monthly creative production (video + static)",
          "Advanced Pixel events + server-side tracking",
          "CRM integration for offline conversions",
          "Daily optimization + weekly dashboard",
          "Dedicated Meta ads specialist",
          "Weekly check-in",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Google Ads bundle at $1,499/mo (save $500)"],
      },
    ],
    comparison: [
      { feature: "Ad sets managed", basic: "2", standard: "5", premium: "Unlimited" },
      { feature: "Monthly ad spend cap", basic: "Up to $3,000", standard: "Up to $10,000", premium: "Unlimited" },
      { feature: "Ad formats", basic: "Static image", standard: "Carousel + video + stories", premium: "All formats + dynamic" },
      { feature: "Custom audiences", basic: "Interest targeting", standard: "Custom + lookalikes", premium: "Advanced + suppression" },
      { feature: "A/B testing", basic: false, standard: true, premium: true },
      { feature: "Retargeting", basic: "Add-on", standard: true, premium: true },
      { feature: "Lead form ads", basic: false, standard: true, premium: true },
      { feature: "Server-side tracking", basic: false, standard: false, premium: true },
      { feature: "CRM offline conversion", basic: false, standard: false, premium: true },
      { feature: "Monthly creative production", basic: false, standard: false, premium: true },
      { feature: "Reporting", basic: "Monthly", standard: "Bi-weekly", premium: "Weekly dashboard" },
    ],
    faqs: [
      { q: "What ad spend do I need for Meta ads to work?", a: "We recommend a minimum of $1,500/mo in spend. The algorithm needs data to optimize — higher budgets learn faster and deliver better cost-per-lead." },
      { q: "Can Meta ads work for medical services?", a: "Yes, with the right compliance approach. We know Meta's healthcare advertising policies and structure campaigns to stay approved while still converting effectively." },
      { q: "Do you create the ad creative?", a: "Standard includes creative direction and static ad design. Premium includes a monthly creative production package (video + static). Basic uses provided creative or we create one static set." },
      { q: "How do you track ROI from Meta ads?", a: "We track lead form submissions, website conversions, call-through rates, and — where CRM integration allows — actual booked appointments tied back to specific campaigns." },
      { q: "What's the difference between Facebook and Instagram ads?", a: "We run placements on both by default. Facebook tends to perform better for 35+ age demographics; Instagram for 18–35. We allocate budget dynamically based on performance data." },
    ],
    timeline: "Campaigns live within 3–5 business days",
    technologies: ["Meta Ads Manager", "Meta Pixel", "Meta Conversions API", "HubSpot", "Zapier", "Looker Studio"],
    support: "Account manager + creative consultation included on Standard and Premium",
    guarantee: "If your CPL doesn't improve vs. your prior campaigns within 60 days, we refund one month of management.",
  },

  // ─── INTEGRATION & INFRASTRUCTURE ───────────────────────────────────────────
  {
    id: "api-integration",
    name: "API Development & Integration",
    category: "Integration",
    tagline: "Connect every system your practice runs on — securely, reliably, and with zero manual data transfer.",
    packages: [
      {
        name: "Basic",
        price: "$3,499",
        period: "one-time",
        description: "Connect 1–2 systems your team uses daily — eliminate double-entry and manual data syncing.",
        features: [
          "1–2 REST API integrations",
          "Basic OAuth / API key authentication",
          "Unidirectional data sync",
          "Error logging & notification alerts",
          "API documentation",
          "10-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Monthly API monitoring from $99/mo", "Additional integration +$999 each"],
      },
      {
        name: "Standard",
        price: "$7,499",
        period: "one-time",
        savings: "Most practices reduce manual admin by 8+ hours / week",
        description: "A multi-system integration hub with bidirectional sync, webhooks, and a monitoring layer.",
        features: [
          "Up to 5 API integrations",
          "Bidirectional real-time sync",
          "Webhook support for event-driven triggers",
          "OAuth 2.0 + secure token management",
          "Data transformation & field mapping",
          "API gateway setup",
          "Integration monitoring dashboard",
          "Full API documentation",
          "21-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["HIPAA-compliant data storage +$499", "Custom reporting connector +$999"],
      },
      {
        name: "Premium",
        price: "$14,999",
        period: "one-time",
        description: "An enterprise integration ecosystem — connecting your EHR, CRM, billing, and operational tools into one intelligent data layer.",
        features: [
          "Unlimited API integrations",
          "Full microservices or iPaaS architecture",
          "HIPAA-compliant data pipelines",
          "FHIR R4 / HL7 healthcare data standards",
          "Real-time data streaming",
          "Enterprise-grade API gateway",
          "99.9% uptime SLA",
          "Advanced monitoring + anomaly detection",
          "90-day post-delivery support",
          "30-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Dedicated support retainer from $1,499/mo"],
      },
    ],
    comparison: [
      { feature: "Number of integrations", basic: "1–2", standard: "Up to 5", premium: "Unlimited" },
      { feature: "Sync direction", basic: "Unidirectional", standard: "Bidirectional", premium: "Real-time bidirectional" },
      { feature: "Webhook support", basic: false, standard: true, premium: true },
      { feature: "HIPAA compliance", basic: "Best-effort", standard: "HIPAA-ready", premium: "Full + BAA" },
      { feature: "FHIR/HL7 support", basic: false, standard: "Partial", premium: "Full FHIR R4" },
      { feature: "API gateway", basic: false, standard: true, premium: "Enterprise-grade" },
      { feature: "Monitoring dashboard", basic: "Error alerts", standard: "Full dashboard", premium: "Anomaly detection" },
      { feature: "Post-delivery support", basic: "30 days", standard: "30 days", premium: "90 days" },
      { feature: "Uptime SLA", basic: "None", standard: "99.5%", premium: "99.9%" },
      { feature: "Delivery time", basic: "10 days", standard: "21 days", premium: "30 days" },
    ],
    faqs: [
      { q: "What systems do you typically integrate?", a: "EHR/EMR systems (Athenahealth, eClinicalWorks, Epic, Kareo), CRMs (HubSpot, Salesforce), billing platforms, payment processors (Stripe), scheduling tools (Calendly, Jane App), and communication tools (Twilio, Vonage)." },
      { q: "Do you work with healthcare data standards like FHIR?", a: "Yes — Premium includes full FHIR R4 support for interoperability with major EHR vendors. Standard includes partial FHIR support for common endpoints." },
      { q: "How do you handle data security in integrations?", a: "All data is encrypted in transit (TLS 1.3) and at rest (AES-256). We use least-privilege access principles and can configure HIPAA-compliant data handling with a signed BAA." },
      { q: "What if the API or a third party system changes?", a: "We monitor your integrations for failures and version changes. Post-delivery support periods cover maintenance; after that, we offer a monitoring retainer." },
      { q: "Can you integrate systems that don't have official APIs?", a: "In many cases, yes — through web scraping, custom data extraction, or middleware solutions. We assess feasibility during a free discovery call." },
    ],
    timeline: "10–30 business days",
    technologies: ["Node.js", "Python", "REST", "GraphQL", "FHIR R4", "HL7", "AWS API Gateway", "Zapier", "n8n"],
    support: "30–90 days post-delivery support based on plan",
    guarantee: "Integration performs as specified or we fix it at no cost during the support period.",
  },

  {
    id: "emr-ehr",
    name: "EMR / EHR Software",
    category: "Integration",
    tagline: "Purpose-built electronic health records for modern healthcare practices — go paperless in weeks, not years.",
    packages: [
      {
        name: "Basic",
        price: "$4,999",
        period: "one-time",
        description: "A fully digital patient record system for solo or small practices ready to eliminate paper charts.",
        features: [
          "1 provider, 1 location",
          "Digital patient charts & records",
          "SOAP note templates",
          "Basic appointment scheduling",
          "Prescription generation (PDF)",
          "Patient demographics & history",
          "Data import from Excel/CSV",
          "Role-based staff access",
          "6-month support included",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Additional provider +$499", "Patient mobile app from $4,999"],
      },
      {
        name: "Standard",
        price: "$9,999",
        period: "one-time",
        savings: "Most practices recover the investment in under 90 days",
        description: "A complete EHR for growing multi-provider practices — scheduling, billing, prescriptions, and patient management unified.",
        features: [
          "Up to 10 providers, 3 locations",
          "Full patient chart management",
          "Custom specialty-specific note templates",
          "Advanced scheduling with provider calendars",
          "Digital prescriptions (DEA-compliant e-prescribing ready)",
          "Billing & invoicing module",
          "Insurance claim tracking",
          "Lab results management",
          "Patient portal (web)",
          "Custom reporting dashboard",
          "1-year support included",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Branded patient mobile app from $9,999", "Telehealth module +$3,999"],
      },
      {
        name: "Premium",
        price: "From $19,999",
        period: "one-time",
        description: "Enterprise EHR for large groups, DSOs, and multi-specialty networks — infinitely scalable, deeply customized.",
        features: [
          "Unlimited providers & locations",
          "Custom clinical workflow builder",
          "Multi-specialty template library",
          "Advanced scheduling with resource management",
          "Full RCM (revenue cycle management)",
          "FHIR R4 / HL7 interoperability",
          "Lab & radiology DICOM viewer",
          "Telemedicine built-in",
          "AI clinical decision support",
          "Custom analytics & business intelligence",
          "White-label branded patient app",
          "2-year support included",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing support retainer from $999/mo", "Staff training workshop from $1,499"],
      },
    ],
    comparison: [
      { feature: "Providers", basic: "1", standard: "Up to 10", premium: "Unlimited" },
      { feature: "Locations", basic: "1", standard: "Up to 3", premium: "Unlimited" },
      { feature: "Patient scheduling", basic: "Basic", standard: "Advanced multi-provider", premium: "Resource management" },
      { feature: "Billing & invoicing", basic: false, standard: true, premium: "Full RCM" },
      { feature: "e-Prescribing", basic: "PDF only", standard: "DEA-compliant ready", premium: "Full e-prescribing" },
      { feature: "Lab results", basic: false, standard: true, premium: "DICOM viewer" },
      { feature: "Patient portal", basic: false, standard: "Web portal", premium: "Web + branded app" },
      { feature: "FHIR/HL7", basic: false, standard: false, premium: true },
      { feature: "Telemedicine", basic: false, standard: "Add-on", premium: true },
      { feature: "AI decision support", basic: false, standard: false, premium: true },
      { feature: "Post-delivery support", basic: "6 months", standard: "1 year", premium: "2 years" },
    ],
    faqs: [
      { q: "Is the EHR HIPAA compliant?", a: "Yes. All patient data is stored on HIPAA-eligible cloud infrastructure, encrypted at rest and in transit, with role-based access controls and full audit logging. We sign a BAA." },
      { q: "How long does implementation take?", a: "Basic: 4–6 weeks. Standard: 8–10 weeks. Premium: 12–16 weeks, depending on custom requirements. We include data migration from your existing records." },
      { q: "Can you migrate our existing patient records?", a: "Yes — data migration is included in all plans. We import from paper scans, Excel/CSV, or your current EHR system." },
      { q: "Does it work for our specialty?", a: "We've built EHRs for dental, dermatology, aesthetic, OB/GYN, orthopedics, and multi-specialty practices. Note templates and workflows are customized per specialty." },
      { q: "Can patients access their records online?", a: "Standard includes a web patient portal. Premium includes a white-labeled mobile app for iOS and Android." },
    ],
    timeline: "4–16 weeks depending on plan and customization",
    technologies: ["Next.js", "PostgreSQL", "AWS", "HL7 FHIR", "Twilio", "Stripe", "Firebase Auth"],
    support: "6 months to 2 years of post-delivery support included by plan",
    guarantee: "HIPAA-compliant or we fix it — guaranteed before final delivery.",
  },

  {
    id: "crm-integration",
    name: "CRM Integration",
    category: "Integration",
    tagline: "Connect your CRM to every patient touchpoint — so your team always has the full picture.",
    packages: [
      {
        name: "Basic",
        price: "$1,999",
        period: "one-time",
        description: "A single CRM integration that keeps your patient leads in sync with your marketing and scheduling tools.",
        features: [
          "1 CRM platform (HubSpot, Salesforce, or Zoho)",
          "Contact & lead import",
          "Basic field mapping",
          "Form-to-CRM auto-capture",
          "Basic email sequence trigger",
          "Setup documentation",
          "10-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: false,
        addOns: ["Additional platform +$799", "Team training session +$299"],
      },
      {
        name: "Standard",
        price: "$3,999",
        period: "one-time",
        savings: "Average team saves 6 hours/week on manual CRM updates",
        description: "Bidirectional CRM sync across 2 platforms with workflow automation and team training.",
        features: [
          "2 CRM platforms connected",
          "Bidirectional real-time data sync",
          "Custom field mapping & data transformation",
          "Lead scoring configuration",
          "Automated follow-up workflow setup",
          "Pipeline stage automation",
          "Team permission & role configuration",
          "Staff training session (2 hours)",
          "30-day post-delivery support",
          "21-business-day delivery",
        ],
        cta: "Start Your Project",
        popular: true,
        addOns: ["Ongoing admin support from $299/mo", "CRM data cleansing +$499"],
      },
      {
        name: "Premium",
        price: "$7,999",
        period: "one-time",
        description: "A multi-CRM intelligence layer with AI lead scoring, custom reporting, and an automation architecture that runs your entire patient lifecycle.",
        features: [
          "Unlimited CRM platforms connected",
          "Real-time multi-directional sync",
          "AI-powered lead scoring & prioritization",
          "Patient journey automation (full lifecycle)",
          "Custom analytics & revenue dashboards",
          "Offline conversion tracking",
          "Integration with ads platforms (Google, Meta)",
          "Dedicated integration engineer",
          "90-day post-delivery support",
          "30-business-day delivery",
        ],
        cta: "Book a Strategy Call",
        popular: false,
        addOns: ["Ongoing automation management from $999/mo"],
      },
    ],
    comparison: [
      { feature: "CRM platforms", basic: "1", standard: "2", premium: "Unlimited" },
      { feature: "Sync direction", basic: "One-way", standard: "Bidirectional", premium: "Multi-directional real-time" },
      { feature: "Custom field mapping", basic: "Basic", standard: "Custom", premium: "Advanced transformation" },
      { feature: "Lead scoring", basic: false, standard: true, premium: "AI-powered" },
      { feature: "Workflow automation", basic: "Basic trigger", standard: "Pipeline automation", premium: "Full lifecycle" },
      { feature: "Ads platform sync", basic: false, standard: false, premium: true },
      { feature: "Custom analytics", basic: false, standard: false, premium: true },
      { feature: "Staff training", basic: false, standard: "2 hours", premium: "Full team training" },
      { feature: "Dedicated engineer", basic: false, standard: false, premium: true },
      { feature: "Post-delivery support", basic: "None", standard: "30 days", premium: "90 days" },
      { feature: "Delivery time", basic: "10 days", standard: "21 days", premium: "30 days" },
    ],
    faqs: [
      { q: "Which CRMs do you support?", a: "We work with HubSpot, Salesforce, Zoho, Pipedrive, ActiveCampaign, Go High Level, and most CRMs with an API. Contact us if yours isn't listed." },
      { q: "Will the integration break if the CRM updates?", a: "We monitor integrations for version changes. Post-delivery support periods cover fixes; after that, we offer an optional monitoring retainer." },
      { q: "Can we connect our CRM to our website forms and ads?", a: "Yes — Standard and Premium include web form capture. Premium adds direct ad platform sync (Google, Meta) for offline conversion tracking." },
      { q: "How is patient data handled for HIPAA?", a: "We follow HIPAA data minimization principles — only the data needed flows between systems, encrypted in transit and at rest." },
      { q: "Do you train our team on the new setup?", a: "Standard includes a 2-hour training session. Premium includes full team training and documentation." },
    ],
    timeline: "10–30 business days",
    technologies: ["HubSpot API", "Salesforce API", "Zoho API", "Zapier", "n8n", "REST", "Node.js"],
    support: "30–90 days post-delivery support based on plan",
    guarantee: "Data syncs accurately as specified, or we fix it free during the support window.",
  },

  // ─── SUPPORT & MAINTENANCE ──────────────────────────────────────────────────
  {
    id: "website-maintenance",
    name: "Website Maintenance",
    category: "Support",
    tagline: "Keep your website fast, secure, and updated — without distracting your team from patient care.",
    packages: [
      {
        name: "Basic",
        price: "$149",
        period: "/ month",
        description: "Essential maintenance for small practice websites — security, uptime, and monthly updates covered.",
        features: [
          "5 hours of dev time / month",
          "Monthly security patches & plugin updates",
          "Uptime monitoring (99.9% alert threshold)",
          "Monthly automated backup",
          "Basic performance check",
          "Monthly maintenance report",
        ],
        cta: "Get Protected",
        popular: false,
        addOns: ["Additional hours at $95/hr", "On-demand content edits billed hourly"],
      },
      {
        name: "Standard",
        price: "$299",
        period: "/ month",
        savings: "Cheaper than one hour of emergency dev work after a breach",
        description: "Proactive maintenance with weekly security scans, content updates, and a monthly strategy call.",
        features: [
          "15 hours of dev time / month",
          "Weekly automated security scans",
          "Core Web Vitals monitoring + alerts",
          "Weekly automated backups",
          "Content updates (text, images, blog posts)",
          "Plugin & CMS updates",
          "Monthly SEO health check",
          "Priority email & chat support",
          "Monthly strategy call (30 min)",
        ],
        cta: "Get Protected",
        popular: true,
        addOns: ["Emergency same-day response +$99/mo", "Quarterly conversion audit +$499"],
      },
      {
        name: "Premium",
        price: "$599",
        period: "/ month",
        description: "Fully managed website operations with unlimited dev hours, 24/7 monitoring, and a dedicated technical manager.",
        features: [
          "Unlimited dev hours",
          "24/7 monitoring with 1-hour incident response",
          "Daily automated backups with 1-click restore",
          "Security firewall + DDoS protection",
          "Unlimited content updates & copy changes",
          "Monthly performance optimization",
          "A/B testing & CRO reviews",
          "Dedicated technical manager",
          "Emergency hotline",
          "Quarterly roadmap planning session",
        ],
        cta: "Get Protected",
        popular: false,
        addOns: ["Annual security penetration test +$999"],
      },
    ],
    comparison: [
      { feature: "Dev hours / month", basic: "5 hours", standard: "15 hours", premium: "Unlimited" },
      { feature: "Security scans", basic: "Monthly", standard: "Weekly", premium: "Daily + firewall" },
      { feature: "Uptime monitoring", basic: "99.9% threshold", standard: "Real-time alerts", premium: "24/7 + incident response" },
      { feature: "Backups", basic: "Monthly", standard: "Weekly", premium: "Daily + 1-click restore" },
      { feature: "Content updates", basic: false, standard: true, premium: "Unlimited" },
      { feature: "CMS / plugin updates", basic: "Monthly", standard: "As needed", premium: "Immediate" },
      { feature: "CRO reviews", basic: false, standard: false, premium: "Quarterly" },
      { feature: "SEO health check", basic: false, standard: "Monthly", premium: "Monthly + tracking" },
      { feature: "Incident response SLA", basic: "Next business day", standard: "4 hours", premium: "1 hour" },
      { feature: "Strategy calls", basic: false, standard: "Monthly", premium: "Quarterly roadmap" },
      { feature: "Dedicated tech manager", basic: false, standard: false, premium: true },
    ],
    faqs: [
      { q: "What counts as a 'dev hour'?", a: "Anything that requires us to edit code or the CMS — content updates, layout tweaks, new page sections, plugin configuration, bug fixes, form changes. Standard and Premium cover far more per month than most practices need." },
      { q: "What happens if we go over our hours?", a: "We notify you before exceeding included hours. Additional time is billed at $95/hr for Basic and Standard. Premium is unlimited." },
      { q: "Do you maintain WordPress and other CMS platforms?", a: "Yes — WordPress, Webflow, Wix, Squarespace, Next.js, and custom-built sites. We maintain whatever you're running." },
      { q: "How quickly do you respond to emergencies?", a: "Basic: next business day. Standard: 4-hour response. Premium: 1-hour emergency response with a dedicated hotline." },
      { q: "Do you take over from a previous developer?", a: "Yes. We audit the codebase during onboarding and fix any legacy technical debt that poses a security or performance risk." },
    ],
    timeline: "Onboarding complete within 2 business days of signing",
    technologies: ["WordPress", "Next.js", "Webflow", "Cloudflare", "Sucuri", "UptimeRobot", "Vercel"],
    support: "Priority email + chat on Standard. Emergency hotline on Premium.",
    guarantee: "If your site goes down due to a maintenance action we took, we fix it and credit your next invoice.",
  },

  {
    id: "speed-optimization",
    name: "Website Speed Optimization",
    category: "Support",
    tagline: "A faster website means more patients — Google ranks it higher, and visitors don't leave before it loads.",
    packages: [
      {
        name: "Basic",
        price: "$599",
        period: "one-time",
        description: "A targeted speed fix for slow websites — address Core Web Vitals and get past Google's performance threshold.",
        features: [
          "Full Core Web Vitals audit (LCP, FID, CLS)",
          "Image compression & WebP conversion",
          "Basic browser caching configuration",
          "Render-blocking resource elimination",
          "PageSpeed score improvement (target: 70+)",
          "Delivery report with before/after scores",
          "5-business-day delivery",
        ],
        cta: "Speed Up My Site",
        popular: false,
        addOns: ["Monthly monitoring +$49/mo"],
      },
      {
        name: "Standard",
        price: "$1,199",
        period: "one-time",
        savings: "Most clients see 20–40% more page sessions after speed improvement",
        description: "A comprehensive performance overhaul — from server response time to third-party script management.",
        features: [
          "Full technical performance audit",
          "Core Web Vitals fixes (LCP, INP, CLS)",
          "CDN setup & configuration (Cloudflare)",
          "Advanced image optimization pipeline",
          "Lazy loading for media & iframes",
          "JavaScript & CSS minification + bundling",
          "Third-party script management",
          "Mobile-specific optimization",
          "PageSpeed target: 85+",
          "10-business-day delivery",
        ],
        cta: "Speed Up My Site",
        popular: true,
        addOns: ["3-month monitoring +$129", "Server upgrade recommendation report +$299"],
      },
      {
        name: "Premium",
        price: "$2,499",
        period: "one-time",
        description: "Enterprise-grade performance engineering — sub-1-second loads, edge caching, and database-level optimization.",
        features: [
          "Deep architecture performance audit",
          "Full Core Web Vitals remediation",
          "Edge CDN deployment (Vercel Edge, Cloudflare Workers)",
          "Server-side rendering or static generation upgrades",
          "Database query optimization",
          "HTTP/3 + Brotli compression",
          "Font subsetting & async loading",
          "Advanced service worker caching",
          "Synthetic monitoring setup (30-day post-delivery)",
          "PageSpeed target: 95+",
          "15-business-day delivery",
        ],
        cta: "Speed Up My Site",
        popular: false,
        addOns: ["Annual performance retainer +$299/mo"],
      },
    ],
    comparison: [
      { feature: "Audit scope", basic: "Core Web Vitals audit", standard: "Full technical audit", premium: "Architecture audit" },
      { feature: "CDN setup", basic: false, standard: "Cloudflare", premium: "Edge CDN (Vercel/Cloudflare Workers)" },
      { feature: "Image optimization", basic: "WebP conversion", standard: "Advanced pipeline", premium: "Full pipeline + formats" },
      { feature: "JavaScript optimization", basic: "Render-blocking fix", standard: "Minification + bundling", premium: "Full SSR/static upgrade" },
      { feature: "Database optimization", basic: false, standard: false, premium: true },
      { feature: "Mobile-specific optimization", basic: false, standard: true, premium: true },
      { feature: "PageSpeed target", basic: "70+", standard: "85+", premium: "95+" },
      { feature: "HTTP/3 + Brotli", basic: false, standard: false, premium: true },
      { feature: "Post-delivery monitoring", basic: false, standard: false, premium: "30 days" },
      { feature: "Delivery time", basic: "5 days", standard: "10 days", premium: "15 days" },
    ],
    faqs: [
      { q: "How much faster will my website be?", a: "Results vary by starting point. Basic clients typically go from a score of 30–50 to 70+. Standard reaches 85+. Premium consistently delivers 95+ PageSpeed scores." },
      { q: "Does speed really affect patient bookings?", a: "Yes — Google research shows that a 1-second improvement in mobile load time can increase conversions by 27%. Slow sites also rank lower in search results." },
      { q: "Do you make changes to my live site?", a: "We work on a staging environment first, test thoroughly, then deploy. Live changes happen only after you approve." },
      { q: "What if the score drops after a future update?", a: "We offer an optional monthly monitoring add-on that alerts you to score drops and includes quarterly tune-ups." },
      { q: "My site is on WordPress — can you still optimize it?", a: "Yes. WordPress, Wix, Webflow, Next.js, or custom-built — we optimize any platform, and will recommend hosting or theme changes if they're the root cause." },
    ],
    timeline: "5–15 business days",
    technologies: ["Cloudflare", "Vercel Edge", "WebPageTest", "Google PageSpeed Insights", "Lighthouse", "GTmetrix"],
    support: "Before/after performance report delivered with every project",
    guarantee: "We guarantee the PageSpeed target for your plan — or we keep optimizing at no charge.",
  },
];

// Only services that have a live page on the website
const ACTIVE_IDS = [
  "healthcare-website",   // /clinic-website-design
  "mobile-app",           // /clinic-mobile-app
  "ai-receptionist",      // /ai-receptionist
  "whatsapp-automation",  // /whatsapp-ai-automation
  "emr-ehr",              // /ehr-platform
  "local-seo",            // /local-seo-for-clinics
  "seo",                  // /seo-for-clinics
  "google-ads",           // /digital-marketing-for-clinics
  "meta-ads",             // /digital-marketing-for-clinics
] as const;

export const pricingServices = allServices.filter((s) =>
  (ACTIVE_IDS as readonly string[]).includes(s.id)
);

export const serviceCategories = ["All", "Web & App", "AI & Automation", "Marketing", "Integration"] as const;
export type ServiceCategory = typeof serviceCategories[number];
