import type { AuditAnswers, BusinessGrowthReport } from "@/lib/businessAuditTypes";

function actionPlanBadge(index: number, total: number): string {
  if (index === 0) return "Quick win";
  if (index <= Math.min(2, total - 2)) return "This month";
  return "This quarter";
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function listHtml(items: string[]) {
  return items.map((item) => `<li>${escapeHtml(item)}</li>`).join("");
}

function buildPrintHtml(report: BusinessGrowthReport, answers: AuditAnswers) {
  const steps = report.nextSteps
    .map(
      (step, i) =>
        `<li><strong>${i + 1}.</strong> ${escapeHtml(step)} <em>(${actionPlanBadge(i, report.nextSteps.length)})</em></li>`
    )
    .join("");

  const services = report.recommendedServices
    .map((s) => `<span class="pill">${escapeHtml(s)}</span>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Business Growth Report — Alliance Tech</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Inter, system-ui, -apple-system, sans-serif;
      color: #00283C;
      padding: 40px 48px;
      max-width: 720px;
      margin: 0 auto;
      line-height: 1.55;
      font-size: 14px;
    }
    .brand { font-size: 11px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #0077A8; margin-bottom: 24px; }
    h1 { font-size: 22px; font-weight: 800; margin-bottom: 8px; }
    h2 { font-size: 15px; font-weight: 800; margin: 28px 0 10px; padding-bottom: 6px; border-bottom: 2px solid #E8F4F8; color: #00283C; }
    .score { font-size: 42px; font-weight: 800; color: #00283C; margin: 16px 0 4px; }
    .score-label { font-size: 10px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: #64748b; }
    .meta { font-size: 12px; color: #64748b; margin-top: 12px; }
    p { color: #334155; margin-bottom: 8px; }
    ul, ol { padding-left: 20px; color: #334155; }
    li { margin-bottom: 8px; }
    .pill { display: inline-block; font-size: 11px; font-weight: 700; padding: 4px 10px; margin: 4px 6px 4px 0; border-radius: 999px; background: #E8F4F8; color: #0077A8; border: 1px solid #cce8f0; }
    em { font-style: normal; font-size: 11px; color: #0077A8; font-weight: 600; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <p class="brand">Alliance Tech · Business Growth Audit</p>
  <h1>Your Growth Report</h1>
  <p class="meta">${escapeHtml(answers.businessType)} · ${escapeHtml(answers.monthlyCustomers)} customers/mo · Budget: ${escapeHtml(answers.marketingBudget)}</p>

  <p class="score">${report.growthScore}<span style="font-size:18px;color:#64748b">/100</span></p>
  <p class="score-label">Growth Score</p>

  <h2>Executive Summary</h2>
  <p>${escapeHtml(report.summary)}</p>

  <h2>Biggest Business Issues</h2>
  <ul>${listHtml(report.biggestIssues)}</ul>

  <h2>Revenue Opportunities</h2>
  <ul>${listHtml(report.opportunities)}</ul>

  <h2>Recommended Services</h2>
  <div>${services}</div>

  <h2>Estimated Timeline</h2>
  <p>${escapeHtml(report.timeline)}</p>

  <h2>Expected ROI</h2>
  <p>${escapeHtml(report.estimatedROI)}</p>

  <h2>Action Plan</h2>
  <ol>${steps}</ol>

  <p class="meta" style="margin-top:32px">Generated by Alliance Tech · alliancetechltd.com</p>
</body>
</html>`;
}

/** Opens print dialog in-page — avoids blank about:blank tabs from window.open + noopener. */
export function printGrowthReport(
  report: BusinessGrowthReport,
  answers: AuditAnswers
) {
  const html = buildPrintHtml(report, answers);

  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.title = "Business Growth Report";
  Object.assign(iframe.style, {
    position: "fixed",
    right: "0",
    bottom: "0",
    width: "0",
    height: "0",
    border: "0",
    opacity: "0",
    pointerEvents: "none",
  });

  document.body.appendChild(iframe);

  const doc = iframe.contentDocument ?? iframe.contentWindow?.document;
  if (!doc) {
    iframe.remove();
    return;
  }

  doc.open();
  doc.write(html);
  doc.close();

  const win = iframe.contentWindow;
  if (!win) {
    iframe.remove();
    return;
  }

  const cleanup = () => {
    window.setTimeout(() => iframe.remove(), 1000);
  };

  const triggerPrint = () => {
    win.focus();
    win.print();
    cleanup();
  };

  if (doc.readyState === "complete") {
    window.setTimeout(triggerPrint, 100);
  } else {
    win.addEventListener("load", () => window.setTimeout(triggerPrint, 100), { once: true });
    window.setTimeout(triggerPrint, 500);
  }
}
